import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {hydrate,emptyDocument,projectData,parseInput} from './model.bundle.mjs';
import {createCycle,createCycleNode} from './cycles.bundle.mjs';

const doc=hydrate(emptyDocument('対戦ルールの設計')),d=createCycle('試合の進行'),other=createCycle('復活の流れ'),phase=createCycleNode('phase',60,110);phase.text='対戦準備';d.nodes=[phase];other.nodes=[createCycleNode('state')];other.nodes[0].text='復帰待ち';
const initial=projectData(doc,{}, {[doc.categories[0]._key]:[d,other]}),out=resolve('test-results/browser');await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1700,height:1100},acceptDownloads:true});page.setDefaultTimeout(12000);
const tests=[],errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().startsWith('http'))requests.push(r.url());});page.on('dialog',dialog=>dialog.accept());
const action=name=>page.locator(`[data-action="${name}"]:visible`).first(),tab=name=>page.locator(`[data-tab="${name}"]`).click(),field=name=>page.locator(`#cycleForm [name="${name}"]`),node=id=>page.locator(`[data-cycle-node="${id}"]`),graph=k=>page.locator(`.graph-node[data-node="${k}"]`);
const diagrams=p=>Object.values(p.cycleDiagrams).flat(),cycle=p=>diagrams(p).find(x=>x.id===d.id);let saveIndex=0,input,event,reference,globalRule,localRule;
async function check(name,fn){await fn();tests.push(name);console.log('PASS '+name);}
async function load(p){await page.locator('#fileInput').setInputFiles({name:'game-rules.usdm-project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});}
async function saved(){const wait=page.waitForEvent('download');await action('save').click();const download=await wait,path=resolve(out,`v111-save-${saveIndex++}.json`);await download.saveAs(path);return JSON.parse(await readFile(path,'utf8'));}
async function apply(){await page.keyboard.press('Control+Enter');}
async function add(kind,text){await page.locator(`[data-action="cycle-add-node"][data-kind="${kind}"]`).click();await field('text').fill(text);await apply();return await page.locator('.cycle-node.selected').getAttribute('data-cycle-node');}
try{
  await page.goto(pathToFileURL(resolve('dist/USDM-Studio.html')).href);
  await check('Tree terminal plus adds schema-valid children and offers a following sibling for leaf specifications',async()=>{
    await tab('graph');const category=await page.locator('.graph-node.category').getAttribute('data-node');await page.locator(`.graph-tail-plus[data-target="${category}"]`).click();await expect(page.locator('#addKind')).toHaveValue('inside:requirement');await action('confirm-add').click();const req=await page.locator('.graph-node.requirement').getAttribute('data-node');await page.locator(`.graph-tail-plus[data-target="${req}"]`).click();await expect(page.locator('#addKind')).toHaveValue('inside:specificationGroup');await action('confirm-add').click();const spec=await page.locator('.graph-node.specification').getAttribute('data-node');await page.locator(`.graph-tail-plus[data-target="${spec}"]`).click();await expect(page.locator('#addKind')).toHaveValue('after:specification');await expect(page.locator('#dialog')).toContainText('仕様は子を持てない');await action('confirm-add').click();await expect(page.locator('.graph-node.specification')).toHaveCount(2);parseInput(JSON.stringify(await saved()));await action('undo').click();await expect(page.locator('.graph-node.specification')).toHaveCount(1);await page.locator(`[data-action="graph-collapse"][data-target="${req}"]`).click();await expect(page.locator(`.graph-tail-plus[data-target="${req}"]`)).toHaveCount(0);
  });
  await load(initial);await tab('graph');await graph('cycle:'+d.id).click();
  await check('Player inputs and game events have distinct editable nodes and retain their details when converted',async()=>{
    input=await add('input','出撃方法を選択する');await expect(node(input).locator('polygon')).toHaveCount(1);await expect(page.locator('#cycleKindHint')).toContainText('入力がない場合');await page.locator('[data-action="cycle-add-detail"][data-kind="behavior"]').click();await field('text').fill('未選択の場合は初期選択で出撃する');await apply();await action('cycle-select-node').click();await field('kind').selectOption('action');await apply();await field('kind').selectOption('input');await apply();assert.equal(cycle(await saved()).nodes.find(n=>n.id===input).details[0].text,'未選択の場合は初期選択で出撃する');event=await add('event','補給物資が出現する');await expect(node(event).locator('polygon')).toHaveCount(1);
  });
  await check('References select and open another diagram from the canvas, without copying its content',async()=>{
    reference=await add('reference','戦闘不能から復活まで');await field('reference').selectOption(other.id);await apply();await expect(node(reference)).toContainText('復活の流れ');await node(reference).locator('[data-action="cycle-open-reference"]').click();await expect(page.locator('.cycle-heading')).toContainText('復活の流れ');await tab('cycle:'+d.id);await node(reference).click();await field('reference').selectOption(d.id);await page.locator('#cycleReferenceFields [data-action="cycle-open-reference"]').click();await expect(page.locator('.cycle-heading')).toContainText('試合の進行');await node(reference).click();await field('reference').selectOption(other.id);await apply();const p=await saved();assert.equal(p.projectVersion,3);assert.equal(diagrams(p).length,2);assert.equal(cycle(p).nodes.find(n=>n.id===reference).reference,other.id);
  });
  await check('Changing a reference into another kind warns before removing its link and undo restores it',async()=>{
    await node(reference).click();await field('description').fill('共通の復活仕様を利用する');await field('kind').selectOption('action');await apply();await expect(page.locator('#dialog')).toContainText('参照先の設定を取り除きます');await action('close-dialog').click();await expect(field('description')).toHaveValue('共通の復活仕様を利用する');await apply();await action('cycle-confirm-kind').click();let n=cycle(await saved()).nodes.find(n=>n.id===reference);assert.equal(n.kind,'action');assert.equal(n.reference,undefined);assert.equal(n.description,'共通の復活仕様を利用する');await action('undo').click();await expect(field('kind')).toHaveValue('reference');await expect(field('reference')).toHaveValue(other.id);
  });
  await check('Rules for the diagram and a node share one editable source, with explicit scope and no extra flow nodes',async()=>{
    await action('cycle-select-diagram').click();await page.locator('[data-action="cycle-add-detail"][data-kind="rule"]').click();await field('text').fill('同点のまま終了した場合は引き分けとする');await apply();globalRule=await page.locator('.cycle-detail-row.active').getAttribute('data-id');await expect(page.locator('.cycle-parent-label')).toContainText('この図全体');await expect(page.locator('.cycle-rule-card').first()).toContainText('図全体');await node(phase.id).click();await page.locator('[data-action="cycle-add-detail"][data-kind="rule"]').click();await field('text').fill('準備中は攻撃できない');await apply();localRule=await page.locator('.cycle-detail-row.active').getAttribute('data-id');await expect(page.locator('.cycle-rule-card')).toHaveCount(2);await expect(page.locator(`.cycle-rule-card[data-id="${localRule}"]`)).toContainText('対戦準備');const p=await saved();assert.equal(cycle(p).nodes.length,4);assert.equal(cycle(p).edges.length,0);assert.equal(cycle(p).details[0].id,globalRule);await page.locator(`.cycle-rule-card[data-id="${localRule}"]`).click();await field('text').fill('準備中は移動できるが攻撃できない');await apply();await expect(page.locator(`.cycle-rule-card[data-id="${localRule}"]`)).toContainText('移動できる');
  });
  await check('Global rules appear in the hierarchy and content view and support nested editing, wrapping and undo',async()=>{
    await tab('graph');const key=`cycle:${d.id}:detail:${globalRule}`;await expect(graph(key)).toHaveClass(/cycleRule/);await page.locator(`.graph-edge-plus[data-target="${key}"]`).click();await expect(page.locator('#cycleInsertKind')).toHaveValue('rule');await page.locator('#cycleInsertPosition').selectOption('wrap');await page.locator('#cycleInsertKind').selectOption('specification');await page.locator('#cycleInsertText').fill('勝敗の扱い');await action('cycle-confirm-hierarchy-insert').click();assert.equal(cycle(await saved()).details[0].children[0].id,globalRule);await action('undo').click();await action('cycle-explorer').click();await page.locator(`.cycle-tree-row[data-node="${key}"] .cycle-tree-link`).click();await expect(field('text')).toHaveValue('同点のまま終了した場合は引き分けとする');await tab('explorer');await expect(page.locator('.cycle-summary')).toContainText(['同点のまま終了した場合は引き分けとする','']);await page.locator(`[data-action="cycle-open-target"][data-detail-id="${globalRule}"]`).click();await expect(page.locator('.cycle-parent-label')).toContainText('この図全体');
  });
  await check('Rule visibility changes preserve invalid drafts and rule deletion is fully reversible',async()=>{
    await field('text').fill('');await action('cycle-toggle-rules').click();await action('cycle-toggle-rules').click();await expect(field('text')).toHaveValue('');await page.locator(`.cycle-rule-card[data-id="${localRule}"]`).click();await expect(page.locator('#dialog')).toContainText('詳細の内容');await action('close-dialog').click();await action('cycle-discard').click();await action('cycle-delete-selection').click();await action('cycle-confirm-delete').click();assert.equal(cycle(await saved()).details.length,0);await expect(page.locator('.cycle-rule-card')).toHaveCount(1);await action('undo').click();await expect(page.locator('.cycle-rule-card')).toHaveCount(2);
  });
  await check('Deleting a referenced diagram keeps the referring node and shows a repairable warning until undo',async()=>{
    await tab('cycle:'+other.id);await action('cycle-select-diagram').click();await action('cycle-delete-diagram').click();await expect(page.locator('#dialog')).toContainText('この図への参照 1 件');await action('cycle-confirm-delete').click();await tab('cycle:'+d.id);await node(reference).click();await expect(node(reference)).toContainText('参照先が見つかりません');await expect(field('reference')).toHaveValue(other.id);await action('validate').click();await expect(page.locator('#dialog')).toContainText('参照先の図が見つかりません');await action('close-dialog').click();await action('undo').click();await expect(node(reference)).toContainText('復活の流れ');
  });
  await check('Branch conditions are reachable above detailed specifications and remain plain-language labels',async()=>{
    await action('cycle-fit').click();await action('cycle-connect').click();await node(input).click();await node(phase.id).click();await expect(page.locator('#cycleForm')).toContainText('遷移条件・きっかけ');await field('label').fill('出撃方法の選択が完了');await apply();await node(input).click();await page.locator('.cycle-transitions [data-direction="outgoing"] button').click();await expect(field('label')).toHaveValue('出撃方法の選択が完了');assert.equal(await page.locator('.inspector-content').evaluate(el=>el.scrollTop),0);
  });
  await check('Cycle terminal plus creates a node and connection together, with cancellation, undo and redo',async()=>{
    const before=(await saved()).cycleDiagrams;await action('cycle-fit').click();await page.locator(`.cycle-tail-plus[data-id="${event}"]`).click();await action('close-dialog').click();assert.deepEqual((await saved()).cycleDiagrams,before);await page.locator(`.cycle-tail-plus[data-id="${event}"]`).click();await page.locator('#cycleTailKind').selectOption('action');await page.locator('#cycleTailText').fill('補給物資を取得する');await page.locator('#cycleTailLabel').fill('プレイヤーが回収する');await action('cycle-confirm-tail').click();const p=await saved(),added=cycle(p).nodes.find(n=>n.text==='補給物資を取得する');assert.ok(cycle(p).edges.some(e=>e.source===event&&e.target===added.id&&e.label==='プレイヤーが回収する'));await expect(page.locator(`.cycle-tail-plus[data-id="${event}"]`)).toHaveCount(0);await expect(page.locator(`.cycle-tail-plus[data-id="${added.id}"]`)).toHaveCount(1);await action('undo').click();assert.deepEqual((await saved()).cycleDiagrams,before);await action('redo').click();assert.deepEqual((await saved()).cycleDiagrams,p.cycleDiagrams);
  });
  await check('Tree terminal plus extends cycle node details and global rules as children',async()=>{
    await tab('graph');await page.locator(`.graph-tail-plus[data-target="cycle:${d.id}:detail:${globalRule}"]`).click();await page.locator('#cycleTailText').fill('引き分けの報酬は参加報酬のみ');await action('cycle-confirm-tail').click();await expect(page.locator('.cycle-parent-label')).toContainText('この図全体');assert.equal(cycle(await saved()).details[0].children[0].text,'引き分けの報酬は参加報酬のみ');await tab('graph');await page.locator(`.graph-tail-plus[data-target="cycle:${d.id}:node:${event}"]`).click();await page.locator('#cycleTailKind').selectOption('specification');await page.locator('#cycleTailText').fill('出現位置は試合開始時に決定する');await action('cycle-confirm-tail').click();assert.equal(cycle(await saved()).nodes.find(n=>n.id===event).details[0].text,'出現位置は試合開始時に決定する');
  });
  await check('Project save, reload, JSON editing and print preview preserve all new content',async()=>{
    const p=await saved();parseInput(JSON.stringify(p));await load(p);await tab('document');await expect(page.locator('.cycle-document')).toContainText('同点のまま終了した場合は引き分けとする');await expect(page.locator('.cycle-document')).toContainText('復帰待ち');await tab('json');const text=await page.locator('#jsonEditor').inputValue();assert.equal(JSON.parse(text).projectVersion,3);await tab('graph');await graph('cycle:'+d.id).click();assert.deepEqual((await saved()).cycleDiagrams,p.cycleDiagrams);await action('cycle-toggle-rules').click();await expect(page.locator('.cycle-rule-card')).toHaveCount(2);
  });
  await check('Game-flow tools and rule cards stay accessible at desktop and narrow widths',async()=>{
    await action('cycle-fit').click();await node(input).click();await page.locator('.layout-controls [data-action="cycle-header"]').click();await page.screenshot({path:resolve('dist/v1.11-game-rules.png'),fullPage:true,style:'#toast{display:none!important}'});for(const width of [1280,960,760]){await page.setViewportSize({width,height:1050});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await expect(action('cycle-toggle-rules')).toBeVisible();await expect(page.locator('[data-action="cycle-add-node"][data-kind="input"]')).toBeVisible();}
  });
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);await writeFile(resolve(out,'v111-results.json'),JSON.stringify({passed:tests.length,tests,errors,requests},null,2));console.log(`${tests.length} v1.11 browser scenarios passed.`);
}finally{await browser.close();}
