import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {hydrate,emptyDocument,projectData,parseInput} from './model.bundle.mjs';
import {createCycle,createCycleNode,createDetail,connectCycle,cycleAnchorPoint} from './cycles.bundle.mjs';

const doc=hydrate(emptyDocument('対戦の流れと接続位置')),d=createCycle('試合の進行'),a=createCycleNode('phase',150,250),b=createCycleNode('decision',500,250),c=createCycleNode('input',500,510);
a.text='対戦準備';b.text='決着したか';c.text='再戦を選ぶ';const detail=createDetail();detail.text='参加者が再戦するかを選択する';c.details=[detail];d.nodes=[a,b,c];const edge=connectCycle(d,a.id,b.id,'準備完了');
const initial=projectData(doc,{}, {[doc.categories[0]._key]:[d]}),out=resolve('test-results/browser');await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1700,height:1100},acceptDownloads:true});page.setDefaultTimeout(12000);
const tests=[],errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().startsWith('http'))requests.push(r.url());});page.on('dialog',dialog=>dialog.accept());
const action=name=>page.locator(`[data-action="${name}"]:visible`).first(),tab=name=>page.locator(`[data-tab="${name}"]`).click(),field=name=>page.locator(`#cycleForm [name="${name}"]`),node=id=>page.locator(`[data-cycle-node="${id}"]`),tail=id=>page.locator(`[data-cycle-tail="${id}"]`),handle=end=>page.locator(`[data-cycle-anchor="${edge.id}"][data-end="${end}"]`),cycle=p=>Object.values(p.cycleDiagrams).flat().find(x=>x.id===d.id);
let saveIndex=0;
async function check(name,fn){await fn();tests.push(name);console.log('PASS '+name);}
async function load(p=initial){await page.locator('#fileInput').setInputFiles({name:'connections.usdm-project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await tab('graph');await page.locator(`.graph-node[data-node="cycle:${d.id}"]`).click();await action('cycle-fit').click();}
async function saved(){const wait=page.waitForEvent('download');await action('save').click();const download=await wait,path=resolve(out,`v112-save-${saveIndex++}.json`);await download.saveAs(path);return JSON.parse(await readFile(path,'utf8'));}
async function selectEdge(id=edge.id){const path=page.locator(`[data-cycle-edge="${id}"] .cycle-edge-hit`),point=await path.evaluate(el=>{const p=el.getPointAtLength(el.getTotalLength()*.27),s=new DOMPoint(p.x,p.y).matrixTransform(el.getScreenCTM());return {x:s.x,y:s.y};});await page.mouse.click(point.x,point.y);await expect(page.locator('.cycle-anchor-handle')).toHaveCount(2);}
async function pointOnNode(id,x,y){const rect=await node(id).boundingBox();return {x:rect.x+x*rect.width/200,y:rect.y+y*rect.height/108};}
async function drag(end,id,x,y,finish=true){const r=await handle(end).boundingBox(),p=await pointOnNode(id,x,y);await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(p.x,p.y,{steps:12});if(finish)await page.mouse.up();}
async function assertHandle(end,n,anchor){const r=await handle(end).boundingBox(),p=cycleAnchorPoint(n,anchor),expected=await pointOnNode(n.id,p.x-n.x,p.y-n.y);assert.ok(Math.abs(r.x+r.width/2-expected.x)<2);assert.ok(Math.abs(r.y+r.height/2-expected.y)<2);}
async function manualProject(){const p=structuredClone(initial),x=cycle(p);p.projectVersion=4;x.edges[0].sourceAnchor={angle:270};x.edges[0].targetAnchor={angle:90};return p;}
try{
  await page.goto(pathToFileURL(resolve('dist/USDM-Studio.html')).href);
  await check('Initial terminal lines can be selected and deleted with Delete without deleting their nodes or specifications',async()=>{
    await load();await tail(c.id).click();await expect(tail(c.id)).toHaveAttribute('aria-pressed','true');await expect(page.locator('.inspector-content')).toContainText('末端の追加用の線');await page.keyboard.press('Delete');await expect(tail(c.id)).toHaveCount(0);await expect(node(c.id)).toBeVisible();await expect(page.locator('#dialog')).not.toBeVisible();const p=await saved(),n=cycle(p).nodes.find(n=>n.id===c.id);assert.equal(n.tailHidden,true);assert.deepEqual(n.details,c.details);assert.equal(cycle(p).edges.length,1);assert.equal(p.projectVersion,4);
    await action('undo').click();await expect(tail(c.id)).toBeVisible();await action('redo').click();await expect(tail(c.id)).toHaveCount(0);await node(c.id).click();await expect(field('showTail')).not.toBeChecked();await field('showTail').check();await page.keyboard.press('Control+Enter');await expect(tail(c.id)).toBeVisible();assert.equal(cycle(await saved()).nodes.find(n=>n.id===c.id).tailHidden,undefined);
  });
  await check('Hidden terminal lines persist through reload and can be restored before using the plus again',async()=>{
    await load();await tail(c.id).focus();await page.keyboard.press('Enter');await page.keyboard.press('Delete');const p=await saved();await load(p);await expect(tail(c.id)).toHaveCount(0);await node(c.id).click();await field('showTail').check();await page.keyboard.press('Control+Enter');await page.locator(`.cycle-tail-plus[data-id="${c.id}"]`).click();await page.locator('#cycleTailText').fill('再戦の準備をする');await action('cycle-confirm-tail').click();const next=cycle(await saved());assert.equal(next.nodes.length,4);assert.ok(next.edges.some(e=>e.source===c.id));await action('undo').click();await expect(tail(c.id)).toBeVisible();
  });
  await check('Selecting a real arrow shows two endpoint handles on the attached nodes',async()=>{
    await load();await selectEdge();await expect(field('label')).toHaveValue('準備完了');await expect(handle('source')).toBeVisible();await expect(handle('target')).toBeVisible();await assertHandle('source',a,{angle:0});await assertHandle('target',b,{angle:180});await expect(action('cycle-reset-anchors')).toBeDisabled();await node(c.id).click();await expect(page.locator('.cycle-anchor-handle')).toHaveCount(0);
  });
  await check('Dragging both endpoint handles adjusts the curve while keeping nodes, conditions and connections intact',async()=>{
    await load();await selectEdge();await drag('source',a.id,100,3);await drag('target',b.id,100,105);const p=await saved(),e=cycle(p).edges[0];assert.ok(Math.abs(e.sourceAnchor.angle-270)<1);assert.ok(Math.abs(e.targetAnchor.angle-90)<1);assert.equal(e.source,a.id);assert.equal(e.target,b.id);assert.equal(e.label,'準備完了');assert.deepEqual(cycle(p).nodes,cycle(initial).nodes);await assertHandle('source',a,e.sourceAnchor);await assertHandle('target',b,e.targetAnchor);
    await action('undo').click();assert.equal(cycle(await saved()).edges[0].targetAnchor,undefined);await action('undo').click();assert.equal(cycle(await saved()).edges[0].sourceAnchor,undefined);await action('redo').click();await action('redo').click();assert.deepEqual(cycle(await saved()).edges,e?cycle(p).edges:[]);
  });
  await check('Endpoint dragging uses graph coordinates when zoomed and scrolled, and stays on its existing node',async()=>{
    await load();await selectEdge();await action('cycle-actual').click();await action('cycle-zoom-in').click();await action('cycle-zoom-in').click();await page.locator('.cycle-viewport').evaluate(el=>{el.scrollLeft=120;el.scrollTop=180;});assert.ok(await page.locator('.cycle-viewport').evaluate(el=>el.scrollTop>0&&el.scrollLeft>0));await drag('source',a.id,40,3);const p=await saved(),e=cycle(p).edges[0];assert.ok(e.sourceAnchor.angle>210&&e.sourceAnchor.angle<260);await assertHandle('source',a,e.sourceAnchor);
    await drag('source',b.id,100,54);const e2=cycle(await saved()).edges[0];assert.equal(e2.source,a.id);await assertHandle('source',a,e2.sourceAnchor);
  });
  await check('Moving a node and changing its shape preserves manual anchors and keeps the endpoint on the new outline',async()=>{
    await load(await manualProject());await node(a.id).click();const from=await pointOnNode(a.id,100,54);await page.mouse.move(from.x,from.y);await page.mouse.down();await page.mouse.move(from.x+55,from.y+35,{steps:10});await page.mouse.up();let p=await saved(),n=cycle(p).nodes.find(n=>n.id===a.id);assert.ok(n.x>a.x+40&&n.y>a.y+20);assert.deepEqual(cycle(p).edges[0].sourceAnchor,{angle:270});await action('cycle-select-diagram').click();await selectEdge();await assertHandle('source',n,{angle:270});await node(b.id).click();await field('kind').selectOption('event');await page.keyboard.press('Control+Enter');await page.locator('.cycle-transitions [data-direction="incoming"] button').click();p=await saved();n=cycle(p).nodes.find(n=>n.id===b.id);assert.equal(n.kind,'event');await assertHandle('target',n,{angle:90});
  });
  await check('Escape and pointer cancellation discard drag previews without saving an endpoint adjustment',async()=>{
    await load(await manualProject());await selectEdge();const p=await saved(),path=await page.locator(`[data-cycle-edge="${edge.id}"] .cycle-edge-line`).getAttribute('d');await drag('source',a.id,100,105,false);await page.keyboard.press('Escape');await page.mouse.up();assert.deepEqual(cycle(await saved()),cycle(p));await expect(page.locator(`[data-cycle-edge="${edge.id}"] .cycle-edge-line`)).toHaveAttribute('d',path);
    await drag('target',b.id,197,54,false);await page.locator('.cycle-viewport').dispatchEvent('pointercancel',{pointerId:1});await page.mouse.up();assert.deepEqual(cycle(await saved()),cycle(p));
  });
  await check('Pending arrow labels are applied before a drag and Delete in a text field only edits text',async()=>{
    await load();await selectEdge();await field('label').fill('出撃の準備が完了');await drag('source',a.id,100,3);assert.equal(cycle(await saved()).edges[0].label,'出撃の準備が完了');await field('label').fill('削除テスト');await field('label').press('Home');await field('label').press('Delete');await expect(field('label')).toHaveValue('除テスト');await expect(page.locator('[data-cycle-edge]')).toHaveCount(1);await expect(page.locator('.cycle-node')).toHaveCount(3);
  });
  await check('Invalid node drafts block line selection and stay editable without changing diagram data',async()=>{
    await load();await node(c.id).click();await field('text').fill('');await tail(c.id).click();await expect(page.locator('#dialog')).toContainText('大まかな仕様・場面');await action('close-dialog').click();await expect(field('text')).toHaveValue('');await expect(tail(c.id)).toHaveAttribute('aria-pressed','false');await action('cycle-discard').click();assert.deepEqual(cycle(await saved()),cycle(initial));
  });
  await check('Automatic positioning can be restored and undone; changing an endpoint node resets only that endpoint',async()=>{
    await load(await manualProject());await selectEdge();await action('cycle-reset-anchors').click();let e=cycle(await saved()).edges[0];assert.equal(e.sourceAnchor,undefined);assert.equal(e.targetAnchor,undefined);await action('undo').click();await expect(action('cycle-reset-anchors')).toBeEnabled();await field('source').selectOption(c.id);await page.keyboard.press('Control+Enter');e=cycle(await saved()).edges[0];assert.equal(e.sourceAnchor,undefined);assert.deepEqual(e.targetAnchor,{angle:90});assert.equal(e.source,c.id);await action('undo').click();e=cycle(await saved()).edges[0];assert.equal(e.source,a.id);assert.deepEqual(e.sourceAnchor,{angle:270});
  });
  await check('Focused handles support keyboard adjustment and selected arrows retain their normal Delete operation',async()=>{
    await load(await manualProject());await selectEdge();await handle('source').focus();await page.keyboard.press('ArrowRight');assert.equal(cycle(await saved()).edges[0].sourceAnchor.angle,275);await handle('target').focus();await page.keyboard.press('Shift+ArrowLeft');assert.equal(cycle(await saved()).edges[0].targetAnchor.angle,75);await handle('target').focus();await page.keyboard.press('Delete');await expect(page.locator('#dialog')).toContainText('選択した矢印を削除');await action('cycle-confirm-delete').click();await expect(page.locator('.cycle-node')).toHaveCount(3);await expect(page.locator('[data-cycle-edge]')).toHaveCount(0);await expect(tail(a.id)).toBeVisible();await action('undo').click();await expect(page.locator('[data-cycle-edge]')).toHaveCount(1);
  });
  await check('Return arrows and self loops expose movable endpoints and retain their labels',async()=>{
    const p=await manualProject(),x=cycle(p),back=connectCycle(x,b.id,a.id,'再戦'),loop=connectCycle(x,b.id,b.id,'続行');await load(p);await node(b.id).click();await page.locator(`.cycle-transitions [data-direction="outgoing"] [data-id="${back.id}"]`).click();await expect(page.locator(`[data-cycle-anchor="${back.id}"]`)).toHaveCount(2);await page.locator(`[data-cycle-anchor="${back.id}"][data-end="target"]`).focus();await page.keyboard.press('ArrowRight');await node(b.id).click();await page.locator(`.cycle-transitions [data-direction="outgoing"] [data-id="${loop.id}"]`).click();await page.locator(`[data-cycle-anchor="${loop.id}"][data-end="source"]`).focus();await page.keyboard.press('ArrowLeft');const next=cycle(await saved());assert.ok(next.edges.find(e=>e.id===back.id).targetAnchor);assert.ok(next.edges.find(e=>e.id===loop.id).sourceAnchor);assert.equal(next.edges.find(e=>e.id===loop.id).label,'続行');await expect(page.locator('.cycle-anchor-handle')).toHaveCount(2);
  });
  await check('Inserting at an adjusted arrow preserves the original nodes endpoint positions and is reversible',async()=>{
    await load(await manualProject());const before=cycle(await saved());await page.locator(`.cycle-edge-plus[data-id="${edge.id}"]`).click();await page.locator('#cycleInsertText').fill('開始を通知する');await action('cycle-confirm-edge-insert').click();const next=cycle(await saved()),first=next.edges.find(e=>e.id===edge.id),second=next.edges.find(e=>e.source===first.target);assert.deepEqual(first.sourceAnchor,{angle:270});assert.equal(first.targetAnchor,undefined);assert.deepEqual(second.targetAnchor,{angle:90});assert.equal(second.target,b.id);await action('undo').click();assert.deepEqual(cycle(await saved()),before);
  });
  await check('Project JSON editing, reload and display keep endpoint and hidden-line settings without extra network activity',async()=>{
    const p=await manualProject();cycle(p).nodes.find(n=>n.id===c.id).tailHidden=true;await load(p);await tab('json');const raw=JSON.parse(await page.locator('#jsonEditor').inputValue());assert.equal(raw.projectVersion,4);cycle(raw).edges[0].targetAnchor.angle=140;await page.locator('#jsonEditor').fill(JSON.stringify(raw,null,2));await action('apply-json').click();const next=await saved();parseInput(JSON.stringify(next));await load(next);await expect(tail(c.id)).toHaveCount(0);await selectEdge();await assertHandle('target',b,{angle:140});assert.deepEqual(cycle(await saved()),cycle(next));await page.screenshot({path:resolve('dist/v1.12-connection-handles.png'),fullPage:true,style:'#toast{display:none!important}'});
    for(const width of [1280,960,760]){await page.setViewportSize({width,height:1100});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await expect(action('cycle-fit')).toBeVisible();}await page.setViewportSize({width:1700,height:1100});
  });
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);await writeFile(resolve(out,'v112-results.json'),JSON.stringify({passed:tests.length,tests,errors,requests},null,2));console.log(`${tests.length} v1.12 browser scenarios passed.`);
}catch(error){await page.screenshot({path:resolve(out,'v112-failure.png'),fullPage:true});throw error;}finally{await browser.close();}
