import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {hydrate,emptyDocument,projectData,parseInput} from './model.bundle.mjs';
import {createCycle,createCycleNode,createDetail,connectCycle} from './cycles.bundle.mjs';
import {parseCycleClipboard} from './cycle-clipboard.bundle.mjs';

const doc=hydrate(emptyDocument('フローのコピー元')),d=createCycle('試合の進行'),a=createCycleNode('input',70,110),b=createCycleNode('decision',390,150),c=createCycleNode('reference',700,150),second=createCycle('同じ文書の別の図');
a.text='参加方法を選ぶ';b.text='準備が完了したか';c.text='復活の流れ';c.reference=second.id;a.tailHidden=true;const detail=createDetail(),rule=createDetail('rule');detail.text='参加者の入力を待つ';rule.text='同じ操作を連続で受け付けない';detail.children=[rule];a.details=[detail];d.nodes=[a,b,c];d.details=[createDetail('rule')];
const edge=connectCycle(d,a.id,b.id,'準備完了');edge.sourceAnchor={angle:0};edge.targetAnchor={angle:180};connectCycle(d,b.id,a.id,'やり直す');connectCycle(d,b.id,b.id,'待機する');connectCycle(d,b.id,c.id,'決定する');
const initial=projectData(doc,{}, {[doc.categories[0]._key]:[d,second]}),targetDoc=hydrate(emptyDocument('独立したコピー先')),target=createCycle('別タブの流れ'),existing=createCycleNode('phase',80,110);existing.text='既存の仕様';target.nodes=[existing];const targetProject=projectData(targetDoc,{}, {[targetDoc.categories[0]._key]:[target]});
const out=resolve('test-results/browser');await mkdir(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});
// Separate browser contexts intentionally have no shared app storage or JavaScript state.
const contexts=await Promise.all([0,1].map(()=>browser.newContext({viewport:{width:1700,height:1100},acceptDownloads:true,permissions:['clipboard-read','clipboard-write']}))),[page,other]=await Promise.all(contexts.map(c=>c.newPage()));
const tests=[],errors=[],requests=[];for(const p of [page,other]){p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('http'))requests.push(r.url());});p.on('dialog',dialog=>dialog.accept());}
const action=(name,p=page)=>p.locator(`[data-action="${name}"]:visible`).first(),node=(id,p=page)=>p.locator(`[data-cycle-node="${id}"]`),field=name=>page.locator(`#cycleForm [name="${name}"]`),tab=(name,p=page)=>p.locator(`[data-tab="${name}"]`).click(),cycle=(p,id=d.id)=>Object.values(p.cycleDiagrams).flat().find(x=>x.id===id);
let saveIndex=0;
async function check(name,fn){await fn();tests.push(name);console.log('PASS '+name);}
async function load(p=page,project=initial,id=d.id){await p.bringToFront();await p.locator('#fileInput').setInputFiles({name:'clipboard-test.usdm-project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await tab('graph',p);await p.locator(`.graph-node[data-node="cycle:${id}"]`).click();await action('cycle-fit',p).click();}
async function saved(p=page){await p.bringToFront();const wait=p.waitForEvent('download');await action('save',p).click();const file=await wait,path=resolve(out,`v113-save-${saveIndex++}.json`);await file.saveAs(path);return JSON.parse(await readFile(path,'utf8'));}
async function clipboard(p=page){await p.bringToFront();return p.evaluate(()=>navigator.clipboard.readText());}
async function writeClipboard(text,p=page){await p.bringToFront();await p.evaluate(text=>navigator.clipboard.writeText(text),text);}
async function nativeCopy(){await page.bringToFront();await page.locator('.cycle-viewport').focus();await page.keyboard.press('Control+c');}
async function nativePaste(p=page){await p.bringToFront();await p.locator('.cycle-viewport').focus();await p.keyboard.press('Control+v');}
async function selectPair(){await node(a.id).click();await node(b.id).click({modifiers:['Control']});await expect(page.locator('.cycle-node.selected')).toHaveCount(2);}
try{
  const url=pathToFileURL(resolve('dist/USDM-Studio.html')).href;await page.goto(url);await other.goto(url);await writeClipboard('USDM Studio synthetic clipboard test');
  await check('Ctrl+A selects every flow node and internal arrow, and the explorer reflects the selection',async()=>{
    await load();await page.locator('.cycle-viewport').focus();await page.keyboard.press('Control+a');await expect(page.locator('.cycle-node.selected')).toHaveCount(3);await expect(page.locator('.cycle-edge.selected')).toHaveCount(4);await expect(page.locator('.cycle-tree-row.selected')).toHaveCount(3);await expect(page.locator('.inspector-content')).toContainText('3 ノードを選択中');await expect(action('cycle-copy')).toBeEnabled();await action('cycle-clear-selection').click();await expect(page.locator('.cycle-node.selected')).toHaveCount(0);await expect(action('cycle-copy')).toBeDisabled();
  });
  await check('Ctrl and Shift clicks add and remove individual nodes, including in the focused explorer',async()=>{
    await selectPair();await node(c.id).click({modifiers:['Shift']});await expect(page.locator('.cycle-node.selected')).toHaveCount(3);await node(b.id).click({modifiers:['Control']});await expect(page.locator('.cycle-node.selected')).toHaveCount(2);await action('cycle-explorer').click();await page.locator(`.cycle-tree-row[data-node="cycle:${d.id}:node:${c.id}"] .cycle-tree-link`).click({modifiers:['Control']});await expect(page.locator('.cycle-node.selected')).toHaveCount(1);await expect(field('text')).toHaveValue(a.text);await node(b.id).click();await expect(page.locator('.cycle-node.selected')).toHaveCount(1);await expect(field('text')).toHaveValue(b.text);
  });
  await check('Native Ctrl+C and Ctrl+V transfer a selection between independent browser tabs with no shared app storage',async()=>{
    await load(other,targetProject,target.id);await load();await selectPair();await nativeCopy();const packet=parseCycleClipboard(await clipboard());assert.equal(packet.nodes.length,2);assert.equal(packet.edges.length,3);assert.deepEqual(packet.nodes[0].details,a.details);await nativePaste(other);await expect(other.locator('.cycle-node')).toHaveCount(3);await expect(other.locator('.cycle-node.selected')).toHaveCount(2);const p=await saved(other),next=cycle(p,target.id),added=next.nodes.filter(n=>n.id!==existing.id);assert.deepEqual(next.nodes[0],existing);assert.equal(next.edges.length,3);assert.equal(added[1].x-added[0].x,b.x-a.x);assert.equal(added[1].y-added[0].y,b.y-a.y);assert.ok(added.every(n=>![a.id,b.id].includes(n.id)));assert.deepEqual(next.edges[0].sourceAnchor,{angle:0});assert.equal(added[0].tailHidden,true);assert.equal(added[0].details[0].children[0].text,rule.text);assert.notEqual(added[0].details[0].id,detail.id);assert.equal(next.details,undefined);assert.equal(cycle(await saved()).nodes.length,3);
  });
  await check('Toolbar Copy and Paste use the shared clipboard and repeated pastes have distinct identities',async()=>{
    await page.bringToFront();await action('cycle-select-all').click();await action('cycle-copy').click();await expect(page.locator('#toast')).toContainText('コピーしました');assert.equal(parseCycleClipboard(await clipboard()).nodes.length,3);await other.bringToFront();await action('cycle-paste',other).click();await expect(other.locator('.cycle-node')).toHaveCount(6);await action('cycle-paste',other).click();await expect(other.locator('.cycle-node')).toHaveCount(9);const next=cycle(await saved(other),target.id);assert.equal(new Set(next.nodes.map(n=>n.id)).size,9);assert.equal(new Set(next.edges.map(e=>e.id)).size,next.edges.length);assert.equal(next.nodes.filter(n=>n.reference===second.id).length,2);await expect(other.locator('.cycle-node.reference').first()).toContainText('参照先が見つかりません');
  });
  await check('Pasting in another diagram within the same document preserves valid reference links',async()=>{
    await page.bringToFront();await action('cycle-select-all').click();await nativeCopy();await tab('graph');await page.locator(`.graph-node[data-node="cycle:${second.id}"]`).click();await nativePaste();await expect(page.locator('.cycle-node')).toHaveCount(3);await expect(page.locator('.cycle-node.reference')).toContainText(second.title);const p=await saved();assert.equal(cycle(p).nodes.length,3);assert.equal(cycle(p,second.id).nodes.length,3);assert.equal(cycle(p,second.id).edges.length,4);
  });
  await check('A paste and a group move each undo and redo as one edit, preserving relative positions and manual anchors',async()=>{
    await load();await selectPair();await nativeCopy();const before=cycle(await saved());await nativePaste();await expect(page.locator('.cycle-node')).toHaveCount(5);const pasted=cycle(await saved());await action('undo').click();assert.deepEqual(cycle(await saved()),before);await action('redo').click();assert.deepEqual(cycle(await saved()),pasted);await action('cycle-select-all').click();await action('cycle-fit').click();const r=await node(a.id).boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+45,r.y+r.height/2+30,{steps:10});await page.mouse.up();const moved=cycle(await saved()),dx=moved.nodes[0].x-pasted.nodes[0].x,dy=moved.nodes[0].y-pasted.nodes[0].y;assert.ok(dx>0&&dy>0);for(let i=0;i<5;i++){assert.equal(moved.nodes[i].x-pasted.nodes[i].x,dx);assert.equal(moved.nodes[i].y-pasted.nodes[i].y,dy);}assert.deepEqual(moved.edges,pasted.edges);await action('undo').click();assert.deepEqual(cycle(await saved()),pasted);
  });
  await check('Delete removes only selected flow nodes and incident arrows, retains diagram-wide rules, and supports Undo',async()=>{
    await load();await selectPair();await page.keyboard.press('Delete');await expect(page.locator('#dialog')).toContainText('2 ノード');await action('cycle-confirm-delete').click();let next=cycle(await saved());assert.equal(next.nodes.length,1);assert.equal(next.nodes[0].id,c.id);assert.equal(next.edges.length,0);assert.deepEqual(next.details,d.details);await action('undo').click();assert.deepEqual(cycle(await saved()),cycle(initial));await action('cycle-select-all').click();await page.keyboard.press('Delete');await action('cycle-confirm-delete').click();await expect(page.locator('.cycle-node')).toHaveCount(0);next=cycle(await saved());assert.deepEqual(next.details,d.details);await action('undo').click();await expect(page.locator('.cycle-node')).toHaveCount(3);
  });
  await check('Text fields retain normal select-all, copy and paste instead of invoking flow operations',async()=>{
    await load();await node(a.id).click();await field('text').focus();await field('text').press('Control+a');await field('text').press('Control+c');assert.equal(await clipboard(),a.text);await field('description').focus();await field('description').press('Control+v');await expect(field('description')).toHaveValue(a.text);await expect(page.locator('.cycle-node.selected')).toHaveCount(1);await expect(page.locator('.cycle-node')).toHaveCount(3);await page.keyboard.press('Control+Enter');await tab('json');await page.locator('#jsonEditor').focus();await page.locator('#jsonEditor').press('Control+a');assert.ok((await page.locator('#jsonEditor').evaluate(el=>el.selectionEnd-el.selectionStart))>100);
  });
  await check('Unapplied properties are copied after validation and invalid drafts block copying without losing the draft',async()=>{
    await load();await node(a.id).click();await field('text').fill('更新したプレイヤー入力');await nativeCopy();assert.equal(parseCycleClipboard(await clipboard()).nodes[0].text,'更新したプレイヤー入力');await field('text').fill('');await action('cycle-copy').click();await expect(page.locator('#dialog')).toContainText('大まかな仕様・場面');await action('close-dialog').click();await expect(field('text')).toHaveValue('');await action('cycle-discard').click();await expect(field('text')).toHaveValue('更新したプレイヤー入力');
  });
  await check('Invalid clipboard data is rejected without changing nodes, details, connections or the current selection',async()=>{
    await load();await selectPair();const before=cycle(await saved());await writeClipboard('{"format":"usdm-studio-cycle-selection","clipboardVersion":1,"nodes":[],"edges":[]}');await nativePaste();await expect(page.locator('#dialog')).toContainText('コピーしたフロー');await action('close-dialog').click();assert.deepEqual(cycle(await saved()),before);await expect(page.locator('.cycle-node.selected')).toHaveCount(2);
  });
  await check('Browser clipboard API denial offers keyboard-based copy and paste instead of a tab-local clipboard',async()=>{
    await load();await selectPair();await page.evaluate(()=>{window.testClipboard=navigator.clipboard;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new DOMException('denied','NotAllowedError');},readText:async()=>{throw new DOMException('denied','NotAllowedError');}}});});await action('cycle-copy').click();await expect(page.locator('#dialog')).toContainText('Ctrl / Cmd＋C');await page.locator('#cycleClipboardText').press('Control+c');await action('close-dialog').click();await action('cycle-paste').click();await expect(page.locator('#dialog')).toContainText('Ctrl / Cmd＋V');await page.locator('#cycleClipboardText').press('Control+v');assert.equal(parseCycleClipboard(await page.locator('#cycleClipboardText').inputValue()).nodes.length,2);await action('cycle-confirm-paste').click();await expect(page.locator('.cycle-node')).toHaveCount(5);await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:window.testClipboard});delete window.testClipboard;});
  });
  await check('A delayed clipboard read cannot paste into a different diagram after tab switching',async()=>{
    await load();await selectPair();await nativeCopy();const payload=await clipboard();await page.evaluate(()=>{window.testClipboard=navigator.clipboard;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:()=>new Promise(resolve=>{window.finishTestPaste=resolve;})}});});await action('cycle-paste').click();await tab('graph');await page.locator(`.graph-node[data-node="cycle:${second.id}"]`).click();await page.evaluate(text=>window.finishTestPaste(text),payload);await expect(page.locator('#toast')).toContainText('貼り付け先が変わりました');await expect(page.locator('.cycle-node')).toHaveCount(0);await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:window.testClipboard});delete window.testClipboard;delete window.finishTestPaste;});assert.equal(cycle(await saved()).nodes.length,3);
  });
  await check('Saved pasted flows reload without a new project format and remain editable in tree and diagram views',async()=>{
    await load();await selectPair();await nativeCopy();await nativePaste();const p=await saved();assert.equal(p.projectVersion,4);parseInput(JSON.stringify(p));await load(page,p);await expect(page.locator('.cycle-node')).toHaveCount(5);await action('cycle-select-all').click();await page.screenshot({path:resolve('dist/v1.13-flow-clipboard.png'),fullPage:true,style:'#toast{display:none!important}'});await tab('graph');const pasted=cycle(p).nodes.find(n=>![a.id,b.id,c.id].includes(n.id));await page.locator(`.graph-node[data-node="cycle:${d.id}:node:${pasted.id}"]`).click();await expect(field('text')).toHaveValue(pasted.text);assert.deepEqual(cycle(await saved()),cycle(p));
  });
  await check('Copy controls remain visible and the page stays within desktop and narrow viewport widths',async()=>{
    for(const width of [1280,960,760]){await page.setViewportSize({width,height:1100});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await expect(action('cycle-select-all')).toBeVisible();await expect(action('cycle-copy')).toBeVisible();await expect(action('cycle-paste')).toBeVisible();}await page.setViewportSize({width:1700,height:1100});
  });
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);await writeFile(resolve(out,'v113-results.json'),JSON.stringify({passed:tests.length,tests,errors,requests},null,2));console.log(`${tests.length} v1.13 browser scenarios passed.`);
}catch(error){await page.screenshot({path:resolve(out,'v113-failure.png'),fullPage:true});throw error;}finally{await browser.close();}
