import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {hydrate,emptyDocument,projectData,parseInput} from './model.bundle.mjs';
import {createCycle,createCycleNode,createDetail,connectCycle,cycleGeometry} from './cycles.bundle.mjs';
import {createLane,plantUml} from '../src/activity.js';

const doc=hydrate(emptyDocument('出荷の流れ')),d=createCycle('出荷アクティビティ','activity'),staff=createLane(d,'出荷担当者'),system=createLane(d,'出荷管理システム');
const spec=createDetail();spec.text='不足がある場合は追加の準備を行う';
const descriptions=[['start','開始',390,110,system],['action','出荷情報の表示',390,260,system],['action','在庫の確認',90,260,staff],['action','出荷準備',90,430,staff],['action','出荷が完了しているか表示',390,430,system],['action','在庫数の水準が適切か表示',390,610,system],['action','在庫数の確認',90,610,staff],['end','終了',90,800,staff]];
d.nodes=descriptions.map(([kind,text,x,y,lane])=>({...createCycleNode(kind,x,y),text,laneId:lane.id}));d.nodes[3].details=[spec];d.nodes.forEach((n,i)=>{if(i)connectCycle(d,d.nodes[i-1].id,n.id,i===4?'準備完了':'');});
const old=createCycle('サイクル図の操作'),a=createCycleNode('input',180,220),b=createCycleNode('action',540,220);old.nodes=[a,b];const oldEdge=connectCycle(old,a.id,b.id,'決定');
const initial=projectData(doc,{}, {[doc.categories[0]._key]:[d,old]}),out=resolve('test-results/browser');await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),contexts=await Promise.all([0,1].map(()=>browser.newContext({viewport:{width:1780,height:1200},acceptDownloads:true,permissions:['clipboard-read','clipboard-write']}))),[page,other]=await Promise.all(contexts.map(c=>c.newPage()));
const tests=[],errors=[],requests=[];for(const p of [page,other]){p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('http'))requests.push(r.url());});p.on('dialog',x=>x.accept());}
const action=(name,p=page)=>p.locator(`[data-action="${name}"]:visible`).first(),field=name=>page.locator(`#cycleForm [name="${name}"]`),node=(id,p=page)=>p.locator(`[data-cycle-node="${id}"]`),diagram=(p,id=d.id)=>Object.values(p.cycleDiagrams).flat().find(x=>x.id===id),tab=(name,p=page)=>p.locator(`[data-tab="${name}"]`).click();let saveIndex=0;
async function check(name,fn){await fn();tests.push(name);console.log('PASS '+name);}
async function load(p=page,project=initial,id=d.id){await p.bringToFront();await p.locator('#fileInput').setInputFiles({name:'activity-test.usdm-project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await tab('graph',p);await p.locator(`.graph-node[data-node="cycle:${id}"]`).click();await action('cycle-fit',p).click();}
async function saved(p=page){await p.bringToFront();const wait=p.waitForEvent('download');await action('save',p).click();const download=await wait,path=resolve(out,`v114-save-${saveIndex++}.json`);await download.saveAs(path);return JSON.parse(await readFile(path,'utf8'));}
async function submit(){await page.locator('#cycleForm button[type="submit"]').click();}
async function selectEdge(id){const selector=page.locator(`[data-cycle-edge="${id}"]`);await selector.focus();await page.keyboard.press('Enter');await expect(page.locator('.cycle-anchor-handle')).toHaveCount(2);}
async function routeDrag(id,dx,dy,finish=true){const path=page.locator(`[data-cycle-edge="${id}"] .cycle-edge-hit`),p=await path.evaluate(el=>{const p=el.getPointAtLength(el.getTotalLength()*.29),s=new DOMPoint(p.x,p.y).matrixTransform(el.getScreenCTM());return {x:s.x,y:s.y};});await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+dx,p.y+dy,{steps:12});if(finish)await page.mouse.up();}
async function moveNode(id,dx,dy){const r=await node(id).boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+dx,r.y+r.height/2+dy,{steps:12});await page.mouse.up();}
async function copyAll(){await page.bringToFront();await action('cycle-select-all').click();await page.locator('.cycle-viewport').focus();await page.keyboard.press('Control+c');}
async function paste(p=page){await p.bringToFront();await p.locator('.cycle-viewport').focus();await p.keyboard.press('Control+v');}
try{
  const url=pathToFileURL(resolve('dist/USDM-Studio.html')).href;await page.goto(url);await other.goto(url);await page.evaluate(()=>navigator.clipboard.writeText('USDM synthetic test'));
  await check('Diagram creation offers cycle and UML modes with an empty initial graph',async()=>{
    await load();await action('cycle-owner').click();await action('cycle-create').click();await page.locator('#cycleDiagramType').selectOption('activity');await page.locator('#cycleTitle').fill('新規UML');await action('cycle-confirm-create').click();await expect(page.locator('.cycle-node')).toHaveCount(0);await expect(field('diagramType')).toHaveValue('activity');const p=await saved(),created=Object.values(p.cycleDiagrams).flat().find(x=>x.title==='新規UML');assert.equal(created.diagramType,'activity');assert.match(created.plantUml,/@startuml/);
  });
  await check('Activity symbols and role swimlanes match the stored graph, while specifications remain in the hierarchy',async()=>{
    await load();await expect(page.locator('.uml-node')).toHaveCount(8);await expect(page.locator('.uml-node.start circle')).toHaveCount(1);await expect(page.locator('.uml-node.end circle')).toHaveCount(2);await expect(page.locator('.cycle-lane')).toHaveCount(2);await expect(page.locator('.cycle-lane-heading').first()).toHaveText('出荷担当者');await node(d.nodes[3].id).click();await expect(page.locator('.inspector-content')).toContainText(spec.text);await action('cycle-owner').click();await expect(page.locator(`.graph-node[data-node="cycle:${d.id}"]`)).toContainText('UMLアクティビティ図');await tab('explorer');await expect(page.locator('.cycle-summary')).toContainText([spec.text,'']);
  });
  await check('UML palette and focused explorer add supported actions, decisions, merges, forks and joins',async()=>{
    await load();for(const kind of ['decision','merge','fork','join'])await page.locator(`[data-action="cycle-add-node"][data-kind="${kind}"]`).click();await action('cycle-explorer').click();await action('cycle-explorer-add').click();const next=diagram(await saved());assert.equal(next.nodes.at(-1).kind,'action');assert.equal(next.nodes.length,13);await expect(page.locator('.activity-issues')).toContainText('分岐先');assert.match(next.plantUml,/===N10===/);
  });
  await check('Multiple selected nodes can be grouped into a new role or assigned together to an existing one',async()=>{
    await load();await node(d.nodes[2].id).click();await node(d.nodes[3].id).click({modifiers:['Control']});await action('cycle-add-lane').click();await page.locator('#cycleLaneName').fill('物流担当');await action('cycle-confirm-lane').click();let next=diagram(await saved()),lane=next.lanes.at(-1);assert.equal(next.nodes[2].laneId,lane.id);assert.equal(next.nodes[3].laneId,lane.id);await action('cycle-fit').click();await node(d.nodes[2].id).click();await node(d.nodes[3].id).click({modifiers:['Control']});await page.locator('#cycleBatchLane').selectOption(system.id);await action('cycle-assign-lane').click();next=diagram(await saved());assert.equal(next.nodes[2].laneId,system.id);assert.equal(next.nodes[3].laneId,system.id);await action('undo').click();assert.equal(diagram(await saved()).nodes[2].laneId,lane.id);
  });
  await check('Role properties rename, resize, reorder and remove a column without deleting its specifications',async()=>{
    await load();await page.locator(`[data-action="cycle-select-lane"][data-id="${staff.id}"]`).click();await field('name').fill('倉庫担当');await field('width').fill('380');await submit();let next=diagram(await saved());assert.equal(next.lanes[0].name,'倉庫担当');assert.equal(next.nodes[1].x,d.nodes[1].x+80);await action('cycle-lane-right').click();next=diagram(await saved());assert.equal(next.lanes[1].id,staff.id);await action('cycle-remove-lane').click();await expect(page.locator('#dialog')).toContainText('ノードと矢印は残し');await action('cycle-confirm-remove-lane').click();next=diagram(await saved());assert.equal(next.nodes.length,8);assert.equal(next.nodes[3].laneId,undefined);assert.deepEqual(next.nodes[3].details,[spec]);await action('undo').click();assert.equal(diagram(await saved()).lanes.length,2);
  });
  await check('Dragging a node across a role boundary changes its role and remains undoable',async()=>{
    await load();const p=await node(d.nodes[2].id).boundingBox();await moveNode(d.nodes[2].id,300*p.width/200,65*p.width/200);const next=diagram(await saved());assert.equal(next.nodes[2].laneId,system.id);assert.equal(next.nodes[2].x,d.nodes[2].x+300);await action('undo').click();assert.equal(diagram(await saved()).nodes[2].laneId,staff.id);
  });
  await check('PlantUML updates after GUI edits, is embedded in JSON, and downloads as a local puml file',async()=>{
    await load();await node(d.nodes[1].id).click();await field('text').fill('出荷情報を確認する');await action('cycle-plantuml').click();await expect(page.locator('#plantUmlSource')).toHaveValue(/出荷情報を確認する/);await expect(page.locator('#plantUmlSource')).toHaveValue(/\|role0\|出荷担当者/);const wait=page.waitForEvent('download');await action('cycle-download-uml').click();const file=await wait,path=resolve(out,'v114-activity.puml');await file.saveAs(path);const source=await readFile(path,'utf8');await action('close-dialog').click();const next=diagram(await saved());assert.equal(source,next.plantUml+'\n');assert.equal(next.plantUml,plantUml(next));
  });
  await check('Switching cycle and UML modes warns about kind conversion and keeps text, details and arrows',async()=>{
    await load(page,initial,old.id);await action('cycle-select-diagram').click();await field('diagramType').selectOption('activity');await submit();await expect(page.locator('#dialog')).toContainText('1 ノードの種類');await action('close-dialog').click();await expect(field('diagramType')).toHaveValue('activity');await submit();await action('cycle-confirm-kind').click();let next=diagram(await saved(),old.id);assert.equal(next.diagramType,'activity');assert.equal(next.nodes[0].kind,'action');assert.equal(next.nodes[0].text,a.text);assert.deepEqual(next.edges,old.edges);await action('undo').click();assert.equal(diagram(await saved(),old.id).nodes[0].kind,'input');
  });
  await check('Native clipboard transfers UML roles, nested specifications and routed arrows across independent browser tabs',async()=>{
    await load();await selectEdge(d.edges[1].id);await routeDrag(d.edges[1].id,10,-45);const original=diagram(await saved());assert.ok(original.edges[1].route);await copyAll();await load(other);await paste(other);await expect(other.locator('.cycle-node')).toHaveCount(16);const next=diagram(await saved(other));assert.equal(next.lanes.length,4);assert.deepEqual(next.nodes[11].details.map(x=>x.text),[spec.text]);assert.deepEqual(next.edges[8].route,original.edges[1].route);assert.notEqual(next.nodes[8].id,d.nodes[0].id);assert.notEqual(next.lanes[2].id,staff.id);
  });
  await check('Cross-mode paste asks before converting unsupported kinds and cancellation does not alter either graph',async()=>{
    await load(page,initial,old.id);await copyAll();await tab('graph');await page.locator(`.graph-node[data-node="cycle:${d.id}"]`).click();await paste();await expect(page.locator('#dialog')).toContainText('ノードを貼り付け先');await action('close-dialog').click();assert.equal(diagram(await saved()).nodes.length,8);await paste();await action('cycle-confirm-convert-paste').click();const next=diagram(await saved());assert.equal(next.nodes.length,10);assert.equal(next.nodes[8].kind,'action');assert.equal(next.nodes[8].text,a.text);
  });
  await check('Dragging a selected line body fixes both endpoints in cycle and UML modes and supports reset, Undo and Redo',async()=>{
    for(const [id,edgeId]of [[old.id,oldEdge.id],[d.id,d.edges[1].id]]){await load(page,initial,id);await selectEdge(edgeId);const before=diagram(await saved(),id),g0=cycleGeometry(before).edges.find(e=>e.id===edgeId);await routeDrag(edgeId,35,55);const next=diagram(await saved(),id),g1=cycleGeometry(next).edges.find(e=>e.id===edgeId);assert.ok(next.edges.find(e=>e.id===edgeId).route);assert.deepEqual(g0.sourcePoint,g1.sourcePoint);assert.deepEqual(g0.targetPoint,g1.targetPoint);assert.notEqual(g0.path,g1.path);assert.deepEqual(next.nodes,before.nodes);await action('undo').click();assert.deepEqual(diagram(await saved(),id),before);await action('redo').click();await selectEdge(edgeId);await action('cycle-reset-route').click();assert.equal(diagram(await saved(),id).edges.find(e=>e.id===edgeId).route,undefined);}
  });
  await check('Escape discards a route preview and endpoint handles still edit the attached node outline',async()=>{
    await load(page,initial,old.id);await selectEdge(oldEdge.id);await routeDrag(oldEdge.id,50,35,false);await page.keyboard.press('Escape');await page.mouse.up();assert.equal(diagram(await saved(),old.id).edges[0].route,undefined);await selectEdge(oldEdge.id);const handle=page.locator(`[data-cycle-anchor="${oldEdge.id}"][data-end="source"]`);await handle.focus();await page.keyboard.press('ArrowDown');assert.equal(diagram(await saved(),old.id).edges[0].sourceAnchor.angle,5);
  });
  await check('JSON save and reload retain UML mode, roles, coordinates, generated source and detailed specifications',async()=>{
    await load();await selectEdge(d.edges[1].id);await routeDrag(d.edges[1].id,35,-35);const p=await saved();parseInput(JSON.stringify(p));await load(page,p);assert.deepEqual(diagram(await saved()),diagram(p));await node(d.nodes[3].id).click();await expect(page.locator('.inspector-content')).toContainText(spec.text);await field('laneId').selectOption('');await submit();assert.equal(diagram(await saved()).nodes[3].laneId,undefined);
  });
  await check('Route dragging accounts for zoom and scrolling, flushes edited conditions and cancels a pointer preview',async()=>{
    const p=structuredClone(initial),flow=diagram(p,old.id);flow.nodes.forEach(n=>{n.x+=800;n.y+=500;});await load(page,p,old.id);await action('cycle-actual').click();await page.locator('.cycle-viewport').evaluate(el=>{el.scrollLeft=750;el.scrollTop=440;});await selectEdge(oldEdge.id);await field('label').fill('変更した条件');await routeDrag(oldEdge.id,40,35);let next=diagram(await saved(),old.id);assert.equal(next.edges[0].label,'変更した条件');assert.deepEqual(next.edges[0].route,{x:40,y:35});await routeDrag(oldEdge.id,35,30,false);await page.locator('.cycle-viewport').dispatchEvent('pointercancel');await page.mouse.up();assert.deepEqual(diagram(await saved(),old.id).edges[0].route,{x:40,y:35});
  });
  await check('UML decision guards use brackets and the selected-line plus still inserts an editable UML action',async()=>{
    await load();await node(d.nodes[1].id).click();await field('kind').selectOption('decision');await submit();await selectEdge(d.edges[1].id);await field('label').fill('T');await submit();await expect(page.locator(`[data-cycle-edge="${d.edges[1].id}"] text`)).toHaveText('[T]');await page.locator(`[data-action="cycle-insert-edge"][data-id="${d.edges[1].id}"]`).click();await expect(page.locator('#cycleInsertKind')).toHaveValue('action');await page.locator('#cycleInsertText').fill('分岐後のアクション');await action('cycle-confirm-edge-insert').click();const next=diagram(await saved());assert.equal(next.nodes.length,9);assert.equal(next.nodes.find(n=>n.text==='分岐後のアクション').kind,'action');assert.equal(next.edges[1].label,'T');
  });
  await check('Activity controls remain usable at desktop and narrow widths without page overflow or external requests',async()=>{
    await load();await action('cycle-fit').click();await page.screenshot({path:resolve('dist/v114-activity.png'),fullPage:true});await page.setViewportSize({width:820,height:1000});await expect(action('cycle-add-lane')).toBeVisible();await expect(action('cycle-plantuml')).toBeVisible();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:resolve('dist/v114-narrow.png'),fullPage:true});
  });
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);await writeFile(resolve(out,'v114-results.json'),JSON.stringify({passed:tests.length,tests,errors,requests},null,2));console.log(`${tests.length} v1.14 browser scenarios passed.`);
}catch(e){await page.screenshot({path:resolve(out,'v114-failure.png'),fullPage:true});console.error(e);process.exitCode=1;}finally{await browser.close();}
