import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {hydrate,emptyDocument,projectData,parseInput} from './model.bundle.mjs';
import {createCycle,createCycleNode,createDetail,connectCycle} from './cycles.bundle.mjs';
import {createLane,laneGeometry} from '../src/lanes.js';
const doc=hydrate(emptyDocument('横向きの役割区画')),d=createCycle('対戦準備','activity'),player=createLane(d,'プレイヤー'),game=createLane(d,'ゲーム');
d.nodes=[createCycleNode('action',90,120),createCycleNode('action',90,340),createCycleNode('action',390,120),createCycleNode('action',390,340)];
d.nodes.forEach((n,i)=>{n.laneId=i<2?player.id:game.id;n.text=['参加を選ぶ','準備を完了する','参加者を登録する','対戦を開始する'][i];});d.nodes[0].details=[createDetail()];d.nodes[0].details[0].text='参加上限に達していたら通知する';[[0,2],[2,1],[1,3]].forEach(([a,b])=>connectCycle(d,d.nodes[a].id,d.nodes[b].id,'完了'));d.edges[0].route={x:20,y:25};
const initial=projectData(doc,{}, {[doc.categories[0]._key]:[d]}),out=resolve('test-results/browser');await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),contexts=await Promise.all([0,1].map(()=>browser.newContext({viewport:{width:1800,height:1200},acceptDownloads:true,permissions:['clipboard-read','clipboard-write']}))),[page,other]=await Promise.all(contexts.map(c=>c.newPage()));
const tests=[],errors=[],requests=[];for(const p of [page,other]){p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('http'))requests.push(r.url());});p.on('dialog',x=>x.accept());}
const action=(name,p=page)=>p.locator(`[data-action="${name}"]:visible`).first(),field=name=>page.locator(`#cycleForm [name="${name}"]`),node=(id,p=page)=>p.locator(`[data-cycle-node="${id}"]`),diagram=p=>Object.values(p.cycleDiagrams).flat()[0],resize=(id,dimension='size')=>page.locator(`[data-lane-resize="${id}"][data-dimension="${dimension}"]`);let saveIndex=0;
async function check(name,fn){await fn();tests.push(name);console.log('PASS '+name);}
async function load(p=page,project=initial){await p.bringToFront();await p.locator('#fileInput').setInputFiles({name:'lanes-test.usdm-project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await p.locator('[data-tab="graph"]').click();await p.locator(`.graph-node[data-node="cycle:${d.id}"]`).click();await action('cycle-fit',p).click();}
async function saved(p=page){await p.bringToFront();const wait=p.waitForEvent('download');await action('save',p).click();const download=await wait,path=resolve(out,`v115-save-${saveIndex++}.json`);await download.saveAs(path);return JSON.parse(await readFile(path,'utf8'));}
async function role(id=player.id){await page.locator(`[data-action="cycle-select-lane"][data-id="${id}"]`).click();}
async function submit(){await page.locator('#cycleForm button[type="submit"]').click();}
async function horizontal(){await role();await field('laneOrientation').selectOption('horizontal');await submit();await action('cycle-fit').click();}
async function dragBorder(id,dimension,delta,finish=true){
  const handle=resize(id,dimension),p=await handle.evaluate(el=>{const b=el.getBoundingClientRect(),v=el.closest('.cycle-viewport').getBoundingClientRect(),axis=el.dataset.resizeAxis;for(let i=1;i<12;i++){const x=axis==='x'?b.x+b.width/2:Math.max(b.x,v.x)+i*(Math.min(b.right,v.right)-Math.max(b.x,v.x))/12,y=axis==='y'?b.y+b.height/2:Math.max(b.y,v.y)+i*(Math.min(b.bottom,v.bottom)-Math.max(b.y,v.y))/12;if(x>v.x&&x<v.right-5&&y>v.y&&y<v.bottom-5&&el.contains(document.elementFromPoint(x,y)))return {x,y,axis,zoom:new DOMMatrix(getComputedStyle(el.closest('.cycle-stage')).transform).a};}return null;});assert.ok(p,'A border must have a reachable drag target');await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+(p.axis==='x'?delta*p.zoom:0),p.y+(p.axis==='y'?delta*p.zoom:0),{steps:12});if(finish)await page.mouse.up();
}
try{
  const url=pathToFileURL(resolve('dist/USDM-Studio.html')).href;await page.goto(url);await other.goto(url);
  await check('Lane properties switch all roles into horizontal rows with left headings and preserve all specifications',async()=>{
    await load();await horizontal();await expect(page.locator('.cycle-lane.horizontal')).toHaveCount(2);await expect(field('width')).toHaveValue('240');await expect(page.locator('#cycleLaneSizing')).toContainText('区画の高さ');const next=diagram(await saved());assert.equal(next.laneOrientation,'horizontal');assert.deepEqual(next.nodes.map(n=>n.laneId),d.nodes.map(n=>n.laneId));assert.deepEqual(next.nodes[0].details,d.nodes[0].details);assert.deepEqual(next.edges,d.edges);const l=await page.locator(`[data-cycle-lane="${player.id}"]`).boundingBox(),h=await page.locator(`[data-action="cycle-select-lane"][data-id="${player.id}"]`).boundingBox();assert.ok(h.height>h.width);assert.ok(h.width<l.width/2);
  });
  await check('Diagram-wide orientation is also available in cycle mode and can return to columns',async()=>{
    const p=structuredClone(initial);diagram(p).diagramType='cycle';delete diagram(p).plantUml;await load(page,p);await action('cycle-select-diagram').click();await field('laneOrientation').selectOption('horizontal');await submit();await expect(page.locator('.cycle-lane.horizontal')).toHaveCount(2);await field('laneOrientation').selectOption('vertical');await submit();await expect(page.locator('.cycle-lane.vertical')).toHaveCount(2);assert.equal(diagram(await saved()).diagramType,'cycle');
  });
  await check('Dragging a column boundary resizes its width, moves the following column and attached arrows, and undoes as one edit',async()=>{
    await load();const before=diagram(await saved()),path=await page.locator(`[data-cycle-edge="${d.edges[0].id}"] .cycle-edge-line`).getAttribute('d');await dragBorder(player.id,'size',80);const next=diagram(await saved());assert.equal(next.lanes[0].width,380);assert.equal(next.nodes[2].x,before.nodes[2].x+80);assert.deepEqual(next.edges,before.edges);assert.notEqual(await page.locator(`[data-cycle-edge="${d.edges[0].id}"] .cycle-edge-line`).getAttribute('d'),path);await action('undo').click();assert.deepEqual(diagram(await saved()),before);await action('redo').click();assert.equal(diagram(await saved()).lanes[0].width,380);
  });
  await check('Dragging row boundaries changes heights and moves later rows while clamping at a usable minimum',async()=>{
    await load();await horizontal();const before=diagram(await saved());await dragBorder(player.id,'size',60);let next=diagram(await saved());assert.equal(next.lanes[0].height,300);assert.equal(next.nodes[2].y,before.nodes[2].y+60);assert.equal(next.nodes[0].x,before.nodes[0].x);await dragBorder(player.id,'size',-170);next=diagram(await saved());assert.equal(next.lanes[0].height,180);await expect(field('width')).toHaveValue('180');
  });
  await check('The outer right edge of rows and bottom edge of columns resize the shared length without moving nodes',async()=>{
    for(const rows of [false,true]){await load();if(rows)await horizontal();await role();await action('cycle-fit').click();const original=Number(await field('laneLength').inputValue()),before=diagram(await saved());await dragBorder(player.id,'length',90);const next=diagram(await saved());assert.equal(next.laneLength,original+90);assert.deepEqual(next.nodes,before.nodes);assert.ok(laneGeometry(next).every(l=>(rows?l.width:l.height)===original+90));}
  });
  await check('Escape and pointer cancellation discard resize previews and leave saved layout unchanged',async()=>{
    await load();const before=diagram(await saved());await dragBorder(player.id,'size',90,false);await page.keyboard.press('Escape');await page.mouse.up();assert.deepEqual(diagram(await saved()),before);await dragBorder(game.id,'size',60,false);await page.locator('.cycle-viewport').dispatchEvent('pointercancel');await page.mouse.up();assert.deepEqual(diagram(await saved()),before);
  });
  await check('Boundary dragging follows diagram coordinates after zoom and scrolling and keyboard resizing supports coarse steps',async()=>{
    await load();await action('cycle-zoom-in').click();await page.locator('.cycle-viewport').evaluate(el=>{el.scrollLeft=60;el.scrollTop=45;});await dragBorder(game.id,'size',73);assert.equal(diagram(await saved()).lanes[1].width,373);await resize(player.id).focus();await page.keyboard.press('Shift+ArrowRight');await page.keyboard.press('ArrowLeft');assert.equal(diagram(await saved()).lanes[0].width,340);
  });
  await check('Pending role edits apply before dragging while invalid role drafts block resizing without losing the draft',async()=>{
    await load();await role();await field('name').fill('参加プレイヤー');await dragBorder(player.id,'size',50);let next=diagram(await saved());assert.equal(next.lanes[0].name,'参加プレイヤー');assert.equal(next.lanes[0].width,350);await field('name').fill('');await dragBorder(player.id,'size',50);await expect(field('name')).toHaveValue('');assert.equal(Number(await resize(player.id).getAttribute('aria-valuenow')),350);if(await page.locator('#dialog').evaluate(el=>el.open))await action('close-dialog').click();await field('name').fill('参加プレイヤー');await submit();
  });
  await check('Horizontal node dragging, row reordering and new roles retain membership and expose up and down controls',async()=>{
    await load();await horizontal();await role();await expect(action('cycle-lane-right')).toHaveText('↓ 下へ');await action('cycle-lane-right').click();const before=diagram(await saved());assert.equal(before.lanes[1].id,player.id);await action('cycle-fit').click();const n=node(d.nodes[0].id),box=await n.boundingBox(),zoom=box.width/200;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2,box.y+box.height/2-240*zoom,{steps:12});await page.mouse.up();assert.equal(diagram(await saved()).nodes[0].laneId,game.id);await action('cycle-add-lane').click();await page.locator('#cycleLaneName').fill('観戦者');await action('cycle-confirm-lane').click();await expect(page.locator('.cycle-lane.horizontal')).toHaveCount(3);assert.equal(diagram(await saved()).lanes[2].height,240);
  });
  await check('JSON reopening and clipboard transfer to another browser tab retain horizontal roles and resized dimensions',async()=>{
    await load();await horizontal();await dragBorder(player.id,'size',70);await role();await field('laneLength').fill('1400');await submit();const p=await saved();parseInput(JSON.stringify(p));await load(page,p);assert.deepEqual(diagram(await saved()),diagram(p));await action('cycle-select-all').click();await page.locator('.cycle-viewport').focus();await page.keyboard.press('Control+c');const empty=structuredClone(initial);diagram(empty).nodes=[];diagram(empty).edges=[];diagram(empty).lanes=[];await load(other,empty);await other.locator('.cycle-viewport').focus();await other.keyboard.press('Control+v');await expect(other.locator('.cycle-lane.horizontal')).toHaveCount(2);const next=diagram(await saved(other));assert.equal(next.lanes[0].height,310);assert.equal(next.laneLength,1400);assert.equal(next.nodes[0].details[0].text,d.nodes[0].details[0].text);
  });
  await check('Rows and their border controls remain usable at desktop and narrow sizes without external requests',async()=>{
    await load();await horizontal();await role();await page.screenshot({path:resolve('dist/v115-horizontal-lanes.png'),fullPage:true});await page.setViewportSize({width:900,height:1000});await action('cycle-fit').click();await role();await expect(field('laneOrientation')).toBeVisible();await expect(field('width')).toBeVisible();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:resolve('dist/v115-narrow.png'),fullPage:true});
  });
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);await writeFile(resolve(out,'v115-results.json'),JSON.stringify({passed:tests.length,tests,errors,requests},null,2));console.log(`${tests.length} v1.15 browser scenarios passed.`);
}catch(e){await page.screenshot({path:resolve(out,'v115-failure.png'),fullPage:true});console.error(e);process.exitCode=1;}finally{await browser.close();}
