import test from 'node:test';
import assert from 'node:assert/strict';
import {hydrate,emptyDocument,walk,Store,projectData,parseInput} from './model.bundle.mjs';
import {createCycle,createCycleNode,createDetail,connectCycle,cloneCycle,cycleGeometry,validateCycleMap,appendCycleNode,insertCycleOnEdge} from './cycles.bundle.mjs';
import {copyCycleSelection,parseCycleClipboard,pasteCycleSelection} from './cycle-clipboard.bundle.mjs';
import {horizontalLanes,laneGeometry,laneAt,laneSize,laneSpan,laneLength,laneLengthLimits,laneSizeLimits,createLane,assignLane,resizeLane,resizeLaneLength,setLaneOrientation,moveLane,removeLane,laneResizePreview} from '../src/lanes.js';
const copy=x=>JSON.parse(JSON.stringify(x));
function fixture(mode='activity'){const doc=hydrate(emptyDocument('役割区画')),owner=doc.categories[0]._key,d=createCycle('対戦の進行',mode),a=createLane(d,'プレイヤー'),b=createLane(d,'ゲーム');d.nodes=[createCycleNode('action',90,120),createCycleNode('action',90,330),createCycleNode('action',390,120),createCycleNode('action',390,330)];d.nodes.forEach((n,i)=>n.laneId=i<2?a.id:b.id);d.nodes[0].details=[createDetail()];d.nodes.slice(1).forEach((n,i)=>connectCycle(d,d.nodes[i].id,n.id,'完了'));d.edges[0].route={x:20,y:30};d.edges[0].sourceAnchor={angle:20};return {doc,owner,d,a,b};}
function within(d){for(const n of d.nodes.filter(n=>n.laneId)){const lane=laneGeometry(d).find(l=>l.id===n.laneId);assert.ok(n.x>=lane.x+(horizontalLanes(d)?180:20));assert.ok(n.y>=lane.y+(horizontalLanes(d)?20:70));if(horizontalLanes(d))assert.ok(n.y+108<=lane.y+lane.height-20);else assert.ok(n.x+200<=lane.x+lane.width-20);}}
test('legacy columns keep their existing widths and horizontal rows use heights with left headings',()=>{const f=fixture(),old=laneGeometry(f.d);assert.deepEqual(old.map(l=>[l.x,l.y,l.width]),[[40,40,300],[340,40,300]]);setLaneOrientation(f.d,'horizontal');const rows=laneGeometry(f.d);assert.deepEqual(rows.map(l=>[l.x,l.y,l.height]),[[40,40,240],[40,280,240]]);assert.equal(laneAt(f.d,240,360).id,f.b.id);assert.equal(laneAt(f.d,240,700),undefined);within(f.d);});
test('switching lane direction maps members into the matching role and reverses without changing content or edges',()=>{for(const mode of ['activity','cycle']){const f=fixture(mode),before=copy(f.d);setLaneOrientation(f.d,'horizontal');within(f.d);assert.deepEqual(f.d.edges,before.edges);assert.deepEqual(f.d.nodes[0].details,before.nodes[0].details);setLaneOrientation(f.d,'vertical');for(let i=0;i<f.d.nodes.length;i++){assert.ok(Math.abs(f.d.nodes[i].x-before.nodes[i].x)<=1);assert.ok(Math.abs(f.d.nodes[i].y-before.nodes[i].y)<=1);}within(f.d);}});
test('column boundary resizing shifts following roles and their connections while keeping member spacing',()=>{const f=fixture(),positions=copy(f.d.nodes),edge=copy(f.d.edges),before=cycleGeometry(f.d);resizeLane(f.d,f.a.id,420);assert.equal(f.d.nodes[2].x,positions[2].x+120);assert.equal(f.d.nodes[3].x,positions[3].x+120);assert.equal(f.d.nodes[0].y,positions[0].y);assert.deepEqual(f.d.edges,edge);assert.notEqual(cycleGeometry(f.d).edges[1].path,before.edges[1].path);within(f.d);});
test('row boundary resizing shifts later rows vertically and preserves node order and spacing',()=>{const f=fixture();setLaneOrientation(f.d,'horizontal');const before=copy(f.d.nodes);resizeLane(f.d,f.a.id,350);assert.equal(f.d.nodes[2].y,before[2].y+110);assert.equal(f.d.nodes[3].y,before[3].y+110);assert.equal(f.d.nodes[1].x-before[0].x,before[1].x-before[0].x);within(f.d);});
test('shrinking a role cannot collapse multiple member nodes onto each other',()=>{const f=fixture();f.a.width=800;f.d.nodes[1].x=500;const limits=laneSizeLimits(f.d,f.a.id);assert.equal(limits.min,650);assert.throws(()=>resizeLane(f.d,f.a.id,300));const gap=f.d.nodes[1].x-f.d.nodes[0].x;resizeLane(f.d,f.a.id,limits.min);assert.equal(f.d.nodes[1].x-f.d.nodes[0].x,gap);within(f.d);});
test('the shared outer edge changes length in either direction without moving nodes and cannot hide members',()=>{const f=fixture();for(const mode of ['vertical','horizontal']){setLaneOrientation(f.d,mode);const before=copy(f.d.nodes),size=laneLengthLimits(f.d).min+300;resizeLaneLength(f.d,size);assert.equal(laneLength(f.d),size);assert.deepEqual(f.d.nodes,before);assert.ok(laneGeometry(f.d).every(l=>(horizontalLanes(f.d)?l.width:l.height)===size));assert.throws(()=>resizeLaneLength(f.d,laneLengthLimits(f.d).min-1));}});
test('horizontal role assignment, reordering, removal and cloning retain specifications and unique ownership',()=>{const f=fixture();setLaneOrientation(f.d,'horizontal');assignLane(f.d,f.d.nodes.slice(0,2).map(n=>n.id),f.b.id);within(f.d);const before=f.d.nodes[0].y;moveLane(f.d,f.b.id,-1);assert.equal(f.d.nodes[0].y,before-240);const clone=cloneCycle(f.d);assert.equal(clone.laneOrientation,'horizontal');assert.notEqual(clone.nodes[0].laneId,f.b.id);removeLane(f.d,f.b.id);assert.equal(f.d.nodes[0].laneId,undefined);assert.equal(f.d.nodes[0].y,340);assert.equal(f.d.nodes[0].details.length,1);});
test('horizontal append and insertion select the role by vertical position and stay clear of the role header',()=>{const f=fixture();setLaneOrientation(f.d,'horizontal');const result=appendCycleNode(f.d,f.d.nodes[1].id),n=f.d.nodes.find(n=>n.id===result.selection.id);assert.equal(n.laneId,f.a.id);assert.ok(n.x>=220);const inserted=insertCycleOnEdge(f.d,f.d.edges[0].id);assert.equal(laneAt(f.d,inserted.node.x+100,inserted.node.y+54)?.id,inserted.node.laneId);within(f.d);});
test('horizontal layouts and both dimensions round-trip as project v7 with atomic validation and undo',()=>{const f=fixture(),store=new Store(f.doc,{}, {[f.owner]:[f.d]}),before=store.snapshot();store.transaction(s=>{const d=s.cycles[f.owner][0];setLaneOrientation(d,'horizontal');resizeLane(d,f.a.id,320);resizeLaneLength(d,1600);});const p=projectData(store.doc,store.labels,store.cycles);assert.equal(p.projectVersion,7);const read=parseInput(JSON.stringify(p));assert.deepEqual(projectData(read.doc,read.labels,read.cycles),p);p.projectVersion=6;assert.throws(()=>parseInput(JSON.stringify(p)),/projectVersion.*7/);store.undo();assert.deepEqual(store.snapshot(),before);store.redo();for(const mutate of [d=>d.laneOrientation='bad',d=>d.laneLength=300,d=>d.lanes[0].height=100,d=>d.lanes[0].height=null]){const state=store.snapshot();assert.throws(()=>store.transaction(s=>mutate(s.cycles[f.owner][0])));assert.deepEqual(store.snapshot(),state);}});
test('tab clipboard preserves horizontal roles and appends repeated copies below existing rows',()=>{const f=fixture();setLaneOrientation(f.d,'horizontal');resizeLane(f.d,f.a.id,320);resizeLaneLength(f.d,1600);const text=copyCycleSelection(f.d,f.d.nodes.map(n=>n.id)),packet=parseCycleClipboard(text),target=createCycle('貼り付け','activity');assert.equal(packet.clipboardVersion,4);pasteCycleSelection(target,text);assert.equal(target.laneOrientation,'horizontal');assert.equal(target.laneLength,1600);within(target);const span=laneSpan(target),before=copy(target.nodes);pasteCycleSelection(target,text);assert.equal(target.nodes[4].y-before[0].y,span);assert.deepEqual(target.nodes[4].details[0].text,before[0].details[0].text);within(target);assert.equal(validateCycleMap(walk(f.doc),{[f.owner]:[target]}),true);packet.clipboardVersion=3;assert.throws(()=>parseCycleClipboard(JSON.stringify(packet)),/形式4/);const noRoles=createCycle();noRoles.laneOrientation='horizontal';noRoles.nodes=[createCycleNode('action')];const noRolesPacket=parseCycleClipboard(copyCycleSelection(noRoles,[noRoles.nodes[0].id]));assert.equal(noRolesPacket.diagramType,'cycle');assert.deepEqual(noRolesPacket.lanes,[]);});
test('pasting between row and column layouts follows the destination direction without losing memberships',()=>{for(const horizontal of [true,false]){const source=fixture(),target=fixture();setLaneOrientation(horizontal?source.d:target.d,'horizontal');pasteCycleSelection(target.d,copyCycleSelection(source.d,source.d.nodes.map(n=>n.id)));assert.equal(horizontalLanes(target.d),!horizontal);assert.equal(target.d.lanes.length,4);assert.equal(target.d.nodes.length,8);within(target.d);assert.equal(validateCycleMap(walk(target.doc),{[target.owner]:[target.d]}),true);}});
test('resize previews do not mutate stored data and geometry contains row and column borders',()=>{const f=fixture();for(const mode of ['vertical','horizontal']){setLaneOrientation(f.d,mode);const before=copy(f.d),preview=laneResizePreview(f.d,f.a.id,'size',500);assert.deepEqual(f.d,before);assert.equal(laneSize(preview,preview.lanes[0]),500);const g=cycleGeometry(preview);for(const l of laneGeometry(preview)){assert.ok(g.width>l.x+l.width);assert.ok(g.height>l.y+l.height);}assert.ok(!/NaN|Infinity/.test(g.edges.map(e=>e.path).join(' ')));}});
