import {CYCLE_OWNERS,CYCLE_KINDS,CYCLE_HINTS,DETAIL_KINDS,CYCLE_NODE,createCycle,createCycleNode,createDetail,connectCycle,removeCycleNode,findCycle,detailRows,detailHolder,cycleRules,cycleGeometry,cycleAnchorAt,cycleAnchorPoint,cycleRows,freeCyclePosition,insertCycleOnEdge,insertCycleHierarchy,appendCycleNode,appendCycleHierarchy} from './cycles.js';
import {copyCycleSelection,pasteCycleSelection} from './cycle-clipboard.js';

export function createCycleUI(ctx){
  const {$,$$,esc,btn,modal,toast,error,state,rows,tab,setTab,render,transact,flush:flushAll,showOwner}=ctx;
  const opened=[],views=new Map();let formDirty=false,cancelGesture=null,hasGesture=()=>false,pendingPaste=null;
  const isActive=()=>tab().startsWith('cycle:');
  const currentId=()=>isActive()?tab().slice(6):'';
  const found=(id=currentId())=>findCycle(state().cycles,id);
  const all=()=>Object.values(state().cycles).flat();
  const ui=(id=currentId())=>{if(!views.has(id))views.set(id,{selection:{kind:'diagram'},zoom:1,left:0,top:0,connect:false,source:'',rulesOpen:false,explorer:{query:'',collapsed:new Set(),top:0}});return views.get(id);};
  function selection(id=currentId()){
    const d=found(id)?.diagram,v=ui(id);if(!d)return {kind:'diagram'};
    let s=v.selection;
    if(s.kind==='edge'&&!d.edges.some(e=>e.id===s.id))s={kind:'diagram'};
    if(s.kind==='node'&&!d.nodes.some(n=>n.id===s.id))s={kind:'diagram'};
    if(s.kind==='nodes')s=nodeSelection([...new Set(s.ids)].filter(id=>d.nodes.some(n=>n.id===id)));
    if(s.kind==='tail'){const n=d.nodes.find(n=>n.id===s.id);if(!n)s={kind:'diagram'};else if(n.tailHidden||d.edges.some(e=>e.source===n.id))s={kind:'node',id:n.id};}
    if(s.kind==='detail'){const holder=s.nodeId?d.nodes.find(n=>n.id===s.nodeId):d;if(!holder)s={kind:'diagram'};else if(!detailRows(holder.details||[]).some(r=>r.item.id===s.id))s=s.nodeId?{kind:'node',id:s.nodeId}:{kind:'diagram'};}
    return v.selection=s;
  }
  function selectedRowKey(){if(!isActive())return '';const s=selection(),prefix='cycle:'+currentId();return prefix+(['node','tail'].includes(s.kind)?':node:'+s.id:s.kind==='detail'?':detail:'+s.id:'');}
  const nodeSelection=ids=>ids.length>1?{kind:'nodes',ids}:ids.length?{kind:'node',id:ids[0]}:{kind:'diagram'};
  function selectedNodeIds(id=currentId()){const s=selection(id);return s.kind==='nodes'?s.ids:s.kind==='node'?[s.id]:[];}
  function isRowSelected(key){if(!isActive())return false;return selection().kind==='nodes'?selectedNodeIds().some(id=>key===`cycle:${currentId()}:node:${id}`):key===selectedRowKey();}
  function sync(){const ids=new Set(all().map(d=>d.id));for(let i=opened.length-1;i>=0;i--)if(!ids.has(opened[i])){views.delete(opened[i]);opened.splice(i,1);}if(isActive()&&!ids.has(currentId())){setTab('graph');formDirty=false;}else if(isActive())ctx.onOpen?.(found().owner);}
  function reset(){opened.length=0;views.clear();formDirty=false;pendingPaste=null;}
  function open(id,target){if(!found(id))return;ctx.onOpen?.(found(id).owner);if(!opened.includes(id))opened.push(id);if(target){ui(id).selection={...target};ui(id).connect=false;ui(id).source='';}setTab('cycle:'+id);render();if(target&&['node','detail'].includes(target.kind))centerNode(target.nodeId||target.id);if(target)$('.inspector-content').scrollTop=0;}
  const explorerState=(id=currentId())=>found(id)?ui(id).explorer:null;
  function close(id){const i=opened.indexOf(id);if(i>=0)opened.splice(i,1);if(currentId()===id)setTab(opened.length?'cycle:'+opened[Math.min(i,opened.length-1)]:'graph');render();}
  function create(owner){if(!rows().some(r=>r.node._key===owner&&CYCLE_OWNERS.has(r.type))){error('カテゴリ・要求グループ・仕様グループを選択してください。');return;}
    const count=(state().cycles[owner]||[]).length;
    modal('サイクル図を追加',`<label class="field">図の名前<input id="cycleTitle" value="${esc('新しいサイクル図'+(count?' '+(count+1):''))}"></label><p class="field-hint">ゲームの流れ、状態遷移、画面遷移などを図にし、各ノードの下に詳細仕様・挙動を追加できます。</p>`,btn('close-dialog','キャンセル')+btn('cycle-confirm-create','作成して編集','plus','primary',`data-owner="${owner}"`));
    $('#cycleTitle').select();
  }
  function tabsHTML(){return opened.map(id=>{const d=found(id)?.diagram;return d?`<div class="cycle-tab ${currentId()===id?'active':''}">${btn('tab','↻ '+esc(d.title),null,`tab ${currentId()===id?'active':''}`,`data-tab="cycle:${id}" title="${esc(d.title)}"`)}${btn('cycle-close','×',null,'cycle-tab-close',`data-id="${id}" aria-label="${esc(d.title)}の編集タブを閉じる"`)}</div>`:'';}).join('');}
  function ownerHTML(owner){if(!CYCLE_OWNERS.has(rows().find(r=>r.node._key===owner)?.type))return '';
    const diagrams=state().cycles[owner]||[];
    return `<div class="inspector-section cycle-owner-section"><h3>サイクル図 <span class="muted">${diagrams.length}</span></h3>${diagrams.map(d=>btn('cycle-open','↻ '+esc(d.title),null,'cycle-owner-link',`data-id="${d.id}"`)).join('')}${btn('cycle-create','サイクル図を追加','plus','',`data-owner="${owner}"`)}</div>`;
  }
  function ownerContentHTML(owner,include=()=>true){
    const ownerRow=rows().find(r=>r.node._key===owner);if(!ownerRow)return '';
    const extra=cycleRows([ownerRow],state().cycles);
    const target=(d,n,item)=>`data-id="${d.id}"${n?` data-node-id="${n.id}"`:''}${item?` data-detail-id="${item.id}"`:''}`;
    const details=(d,n,items)=>items.length?`<ul class="cycle-summary-details">${items.map(item=>`<li>${btn('cycle-open-target',`<span class="cycle-detail-kind ${item.kind}">${DETAIL_KINDS[item.kind]}</span><span>${esc(item.text)}</span>`,null,'cycle-summary-detail',target(d,n,item))}${details(d,n,item.children)}</li>`).join('')}</ul>`:'';
    return (state().cycles[owner]||[]).filter(d=>include(ownerRow)||extra.some(r=>r.diagram.id===d.id&&include(r))).map(d=>`<section class="cycle-summary" data-cycle-summary="${d.id}"><div class="cycle-summary-heading"><h3>↻ ${esc(d.title)}</h3>${btn('cycle-open-target','図で編集',null,'',target(d))}</div>${d.description?`<p class="cycle-summary-description">${esc(d.description)}</p>`:''}${d.details?.length?`<div class="cycle-summary-node"><h4>図全体の仕様・ルール</h4>${details(d,null,d.details)}</div>`:''}${d.nodes.map(n=>`<article class="cycle-summary-node" data-cycle-summary-node="${n.id}">${btn('cycle-open-target',`<span class="cycle-summary-kind ${n.kind}">${CYCLE_KINDS[n.kind]}</span><strong>${esc(n.text)}</strong>`,null,'cycle-summary-node-title',target(d,n))}${n.description?`<p class="cycle-summary-description">${esc(n.description)}</p>`:''}${n.kind==='reference'?referenceSummary(n,d):''}${details(d,n,n.details)}${d.edges.filter(e=>e.source===n.id).map(e=>btn('cycle-open-target',`<span>→ ${esc(d.nodes.find(x=>x.id===e.target)?.text)}</span><small>${esc(e.label||'条件なし')}</small>`,null,'cycle-summary-transition',`data-id="${d.id}" data-edge-id="${e.id}"`)).join('')}</article>`).join('')||'<p class="cycle-summary-description">フロー仕様はまだありません。「図で編集」から追加できます。</p>'}</section>`).join('');
  }
  function transitionsHTML(d,n){return `<div class="inspector-section cycle-transitions"><h3>このノードの遷移</h3><p class="field-hint">出る矢印を選ぶと、条件・きっかけを編集できます。</p>${[['incoming','入る',e=>e.target===n.id],['outgoing','出る',e=>e.source===n.id]].map(([direction,label,filter])=>`<div class="cycle-transition-group" data-direction="${direction}"><h4>${label}（${d.edges.filter(filter).length}）</h4>${d.edges.filter(filter).map(e=>btn('cycle-select-edge',`<span>${esc(d.nodes.find(x=>x.id===(direction==='incoming'?e.source:e.target))?.text)}</span><small>${esc(e.label||'条件なし')}</small>`,null,'cycle-transition-link',`data-id="${e.id}"`)).join('')||'<p class="field-hint">接続はありません。</p>'}</div>`).join('')}</div>`;}
  const field=(label,name,value,area=false,extra='')=>`<label class="field">${label}${area?`<textarea name="${name}" ${extra}>${esc(value)}</textarea>`:`<input name="${name}" value="${esc(value)}" ${extra}>`}</label>`;
  const options=(obj,value)=>Object.entries(obj).map(([key,label])=>`<option value="${key}" ${key===value?'selected':''}>${label}</option>`).join('');
  function detailOutline(n,s,nodeId){return detailRows(n.details||[]).map(r=>`<button type="button" data-action="cycle-select-detail" data-node-id="${nodeId}" data-id="${r.item.id}" class="cycle-detail-row ${s.kind==='detail'&&s.id===r.item.id?'active':''}" style="padding-left:${8+Math.min(r.depth,12)*13}px"><span class="cycle-detail-kind ${r.item.kind}">${DETAIL_KINDS[r.item.kind]}</span><span>${esc(r.item.text)}</span></button>`).join('');}
  function referenceTitle(n){return n.reference?(found(n.reference)?.diagram.title||'参照先が見つかりません'):'参照先を選択してください';}
  function referenceSummary(n,d){return `<p class="cycle-reference-summary">参照先：${esc(referenceTitle(n))}${found(n.reference)?btn('cycle-open-reference','参照先を開く','open','',`data-id="${n.reference}" data-source-diagram="${d.id}" data-source-node="${n.id}"`):''}</p>`;}
  function inspectorHTML(){
    const f=found();if(!f)return '';const d=f.diagram,s=selection(),nodeId=['node','tail'].includes(s.kind)?s.id:s.nodeId||'',n=nodeId?d.nodes.find(n=>n.id===nodeId):null,holder=n||d;
    if(s.kind==='nodes'){const ids=new Set(s.ids),nodes=d.nodes.filter(n=>ids.has(n.id)),edges=d.edges.filter(e=>ids.has(e.source)&&ids.has(e.target));return `<div class="cycle-property-nav">${btn('cycle-select-diagram','↻ '+esc(d.title),null,'ghost')}</div><h3>${nodes.length} ノードを選択中</h3><p class="field-hint">内部の矢印 ${edges.length} 本・詳細 ${nodes.reduce((count,n)=>count+detailRows(n.details).length,0)} 件を一緒にコピーします。</p><p class="field-hint">Ctrl / Cmd・Shift＋クリックで選択を追加・解除できます。選択中のノードをドラッグするとまとめて移動します。</p><div class="cycle-detail-actions">${btn('cycle-copy','コピー')}${btn('cycle-paste','貼り付け')}${btn('cycle-clear-selection','選択解除')}</div><div class="cycle-selection-list">${nodes.map(n=>btn('cycle-select-node',esc(n.text),null,'cycle-owner-link',`data-id="${n.id}"`)).join('')}</div><div class="inspector-section">${btn('cycle-delete-selection','選択したノードを削除','trash','danger')}</div>`;}
    if(s.kind==='tail')return `<div class="cycle-property-nav">${btn('cycle-select-node',esc(n.text),null,'ghost',`data-id="${n.id}"`)}</div><h3>末端の追加用の線</h3><p class="field-hint">Deleteキーでこの線と「＋」を削除できます。ノードと詳細仕様は残ります。</p><p class="field-hint">再表示するには、ノードのプロパティで「末端の追加用の線と＋を表示」をオンにします。</p>${btn('cycle-delete-selection','追加用の線を削除','trash','danger')}`;
    let html=`<div class="cycle-property-nav">${btn('cycle-select-diagram','↻ '+esc(d.title),null,'ghost')}${btn('cycle-owner','所属グループへ',null,'ghost')}</div><form id="cycleForm" data-cycle-id="${d.id}" data-kind="${s.kind}"><div class="node-kind"><span class="type-icon cycle">↻</span>${s.kind==='diagram'?'サイクル図':s.kind==='edge'?'遷移・条件':s.kind==='detail'?'仕様・ルール':'フローノード'}</div>`;
    if(s.kind==='diagram')html+=field('図の名前','title',d.title)+field('図の目的・対象範囲','description',d.description,true,'rows="4"')+`<label class="field">所属グループ<select name="owner">${rows().filter(r=>CYCLE_OWNERS.has(r.type)).map(r=>`<option value="${r.node._key}" ${r.node._key===f.owner?'selected':''}>${esc(rows().filter(a=>a.type!=='document'&&(a.path===r.path||r.path.startsWith(a.path+'/'))).map(a=>a.node.id||a.node.name||a.node.requirement).join(' › '))}</option>`).join('')}</select></label>`;
    else if(s.kind==='edge'){const e=d.edges.find(e=>e.id===s.id);html+=['source','target'].map((key,i)=>`<label class="field">${i?'遷移先':'遷移元'}<select name="${key}">${d.nodes.map(n=>`<option value="${n.id}" ${e[key]===n.id?'selected':''}>${esc(n.text)}</option>`).join('')}</select></label>`).join('')+field('遷移条件・きっかけ','label',e.label,true,'rows="4" placeholder="例：決定を押す／制限時間に達する／T：成立／F：不成立"')+`<p class="field-hint">両端の丸をドラッグすると、接続中のノードの輪郭上で位置を調整できます。丸にフォーカスして矢印キーでも調整できます。Escでドラッグを中止します。</p>${btn('cycle-reset-anchors','接続位置を自動に戻す',null,'',`data-id="${e.id}" ${e.sourceAnchor||e.targetAnchor?'':'disabled'}`)}`;}
    else if(s.kind==='node')html+=`<label class="field">種類<select name="kind">${options(CYCLE_KINDS,n.kind)}</select></label><p id="cycleKindHint" class="field-hint">${esc(CYCLE_HINTS[n.kind]||'大まかな流れを書き、細則は下の詳細仕様・ルールに追加できます。')}</p>`+field('大まかな仕様・場面','text',n.text,true,'rows="3"')+field('概要・補足','description',n.description,true,'rows="3"')+`<div id="cycleReferenceFields" ${n.kind==='reference'?'':'hidden'}><label class="field">参照先の図<select name="reference"><option value="">未設定</option>${n.reference&&!found(n.reference)?`<option value="${esc(n.reference)}" selected>参照先が見つかりません（${esc(n.reference)}）</option>`:''}${all().map(x=>`<option value="${x.id}" ${x.id===n.reference?'selected':''}>${esc(x.title)} — ${esc(rows().find(r=>r.node._key===found(x.id).owner)?.node.name||'')}${x.id===d.id?'（この図）':''}</option>`).join('')}</select></label>${n.kind==='reference'?referenceSummary(n,d):''}</div><div class="cycle-coordinates">${field('X','x',n.x,false,'type="number" min="0" max="20000"')}${field('Y','y',n.y,false,'type="number" min="0" max="20000"')}</div>`;
    else {const row=detailRows(holder.details||[]).find(r=>r.item.id===s.id),blocked=new Set([row.item.id,...detailRows(row.item.children).map(r=>r.item.id)]);html+=`<p class="cycle-parent-label">適用範囲：${esc(n?n.text:'この図全体：'+d.title)}</p><label class="field">種類<select name="kind">${options(DETAIL_KINDS,row.item.kind)}</select></label>`+field('詳細の内容','text',row.item.text,true,'rows="6"')+`<label class="field">ぶら下げる先<select name="detailParent"><option value="">${n?'フローノード':'図全体'}直下</option>${detailRows(holder.details||[]).filter(r=>!blocked.has(r.item.id)).map(r=>`<option value="${r.item.id}" ${row.parent?.id===r.item.id?'selected':''}>${esc(r.item.text)}</option>`).join('')}</select></label>`;}
    if(s.kind==='node')html+=`<label class="cycle-tail-setting"><input type="checkbox" name="showTail" ${n.tailHidden?'':'checked'}>末端の追加用の線と＋を表示</label><p class="field-hint">出る矢印がないときに表示します。</p>`;
    html+=`<div class="edit-actions"><button type="submit" class="primary">変更を適用</button>${btn('cycle-discard','取り消す')}</div><p id="cycleEditState" class="field-hint">変更は適用または選択切り替え時に反映します。</p></form>`;
    if(n)html+=transitionsHTML(d,n);
    if(s.kind!=='edge')html+=`<div class="inspector-section"><h3>${n?'詳細仕様・挙動・ルール':'図全体の仕様・ルール'}</h3><p class="field-hint">${s.kind==='detail'?'選択中の詳細の下に追加します。':n?'このノードに適用する内容を追加します。':'図全体に適用する内容を追加します。'} ルールは進行順を持たず、図の「ルール一覧」でも確認できます。</p><div class="cycle-detail-actions">${btn('cycle-add-detail','仕様を追加','plus','',`data-kind="specification"`)}${btn('cycle-add-detail','挙動を追加','plus','',`data-kind="behavior"`)}${btn('cycle-add-detail','ルールを追加','plus','',`data-kind="rule"`)}</div>${detailOutline(holder,s,nodeId)||'<p class="cycle-detail-empty">大まかな流れを決めてから、必要な仕様やルールを追加できます。</p>'}${s.kind==='detail'?`<div class="flex">${btn('cycle-detail-up','↑ 上へ')}${btn('cycle-detail-down','↓ 下へ')}${btn(n?'cycle-select-node':'cycle-select-diagram',n?'ノードへ戻る':'図全体へ戻る',null,'ghost',`data-id="${nodeId}"`)}</div>`:''}</div>`;
    html+=`<div class="inspector-section">${s.kind==='diagram'?btn('cycle-delete-diagram','この図を削除','trash','danger'):btn('cycle-delete-selection','選択した'+(s.kind==='edge'?'矢印':s.kind==='detail'?'詳細':'ノード')+'を削除','trash','danger')}</div>`;
    return html;
  }
  function flush(allowReferenceLoss=false){
    if(!formDirty)return true;const form=$('#cycleForm');if(!form)return true;const id=form.dataset.cycleId,f=found(id);if(!f)return false;
    const s={...selection(id)},data=new FormData(form),old=s.kind==='node'?f.diagram.nodes.find(n=>n.id===s.id):null;
    if(old?.kind==='reference'&&old.reference&&data.get('kind')!=='reference'&&!allowReferenceLoss){modal('種類の変更を確認',`<p>「別フロー参照」から種類を変更すると、参照先の設定を取り除きます。参照先の図、本文、補足、詳細仕様・ルール、矢印は残ります。</p>`,btn('close-dialog','編集に戻る')+btn('cycle-confirm-kind','警告を確認して変更',null,'primary'));return false;}
    formDirty=false;
    const ok=transact(store=>{
      const f=findCycle(store.cycles,id),d=f.diagram;
      if(s.kind==='diagram'){d.title=data.get('title').trim();d.description=data.get('description');const owner=data.get('owner');if(owner!==f.owner){store.cycles[f.owner]=store.cycles[f.owner].filter(x=>x.id!==id);(store.cycles[owner]??=[]).push(d);}}
      else if(s.kind==='edge'){const e=d.edges.find(e=>e.id===s.id);for(const end of ['source','target']){if(e[end]!==data.get(end))delete e[end+'Anchor'];e[end]=data.get(end);}e.label=data.get('label');}
      else if(s.kind==='node'){const n=detailHolder(d,s.id);n.kind=data.get('kind');n.text=data.get('text');n.description=data.get('description');n.x=Number(data.get('x'));n.y=Number(data.get('y'));if(n.kind==='reference')n.reference=data.get('reference')||'';else delete n.reference;if(data.has('showTail'))delete n.tailHidden;else n.tailHidden=true;}
      else {const holder=detailHolder(d,s.nodeId),details=detailRows(holder.details||[]),row=details.find(r=>r.item.id===s.id),parent=data.get('detailParent');row.item.kind=data.get('kind');row.item.text=data.get('text');if(parent!==(row.parent?.id||'')){const blocked=new Set([row.item.id,...detailRows(row.item.children).map(r=>r.item.id)]);if(blocked.has(parent))throw Error('自分自身や子孫の下には移動できません。');const list=parent?details.find(r=>r.item.id===parent)?.item.children:holder.details;if(!list)throw Error('詳細の移動先がありません。');row.list.splice(row.index,1);list.push(row.item);}}
    });
    if(!ok)formDirty=true;return ok;
  }
  function hierarchyInsertDialog(key){
    const r=cycleRows(rows(),state().cycles).find(r=>r.node._key===key);if(!r)return;
    const kinds=r.type==='cycle'?null:r.selection.kind==='node'?CYCLE_KINDS:DETAIL_KINDS,kind=r.selection.kind==='node'?r.diagram.nodes.find(n=>n.id===r.selection.id).kind:r.type==='cycleBehavior'?'behavior':r.type==='cycleRule'?'rule':'specification';
    modal('枝に要素を挿入',`<p class="graph-insert-context">${esc(r.parent.title||r.parent.name||r.parent.id)}<br>↓<br>${esc(r.node.title)}</p><label class="field">挿入方法<select id="cycleInsertPosition"><option value="before">同じ階層の直前に挿入</option><option value="after" selected>同じ階層の直後に挿入</option>${r.selection.kind==='detail'?'<option value="wrap">間に詳細を挿入し、既存の項目をその子にする</option>':''}</select></label>${kinds?`<label class="field">種類<select id="cycleInsertKind">${options(kinds,kind)}</select></label>`:''}<label class="field">${kinds?'内容':'図の名前'}<input id="cycleInsertText" value="${esc('新しい'+(kinds?kinds[kind]:'サイクル図'))}"></label><p class="field-hint">操作対象の階層：${esc(r.label)}${r.selection.kind==='node'?'。図内の矢印の途中への挿入は、編集タブの矢印の＋を使います。':''}</p>`,btn('close-dialog','キャンセル')+btn('cycle-confirm-hierarchy-insert','挿入する','plus','primary',`data-target="${key}"`));
    $('#cycleInsertText').select();
  }
  function edgeInsertDialog(id){const d=found()?.diagram,e=d?.edges.find(e=>e.id===id);if(!e)return;
    modal('矢印の途中にノードを挿入',`<p class="graph-insert-context">${esc(d.nodes.find(n=>n.id===e.source)?.text)}<br>↓ ${esc(e.label)}<br>${esc(d.nodes.find(n=>n.id===e.target)?.text)}</p><label class="field">種類<select id="cycleInsertKind">${options(CYCLE_KINDS,'phase')}</select></label><label class="field">内容<input id="cycleInsertText" value="新しいフェーズ・場面"></label><p class="field-hint">元の接続を「遷移元 → 新しいノード → 遷移先」に変更します。既存の条件は最初の矢印に引き継ぎます。</p>`,btn('close-dialog','キャンセル')+btn('cycle-confirm-edge-insert','挿入する','plus','primary',`data-id="${id}" data-diagram="${d.id}"`));$('#cycleInsertText').select();
  }
  function tailDialog(key,hierarchy=false){
    const row=hierarchy?cycleRows(rows(),state().cycles).find(r=>r.node._key===key):null,d=hierarchy?row?.diagram:found()?.diagram,n=hierarchy?null:d?.nodes.find(n=>n.id===key);if(!d||hierarchy&&!row||!hierarchy&&!n)return;
    const kinds=!hierarchy||row.type==='cycle'?CYCLE_KINDS:DETAIL_KINDS,kind=kinds===CYCLE_KINDS?'phase':'specification';
    modal('末端に要素を追加',`<p class="field-hint">操作対象の階層：${esc(hierarchy?row.node.title:n.text)}</p><label class="field">種類<select id="cycleTailKind">${options(kinds,kind)}</select></label><label class="field">内容<input id="cycleTailText" value="${esc('新しい'+kinds[kind])}"></label>${hierarchy?'<p class="field-hint">選択した項目の子として追加します。</p>':'<label class="field">矢印の条件・きっかけ（任意）<input id="cycleTailLabel" placeholder="例：入力完了／T：成立／時間切れ"></label><p class="field-hint">新しいノードを作り、元のノードから矢印でつなぎます。</p>'}`,btn('close-dialog','キャンセル')+btn('cycle-confirm-tail','追加してつなぐ','plus','primary',`data-target="${key}" data-diagram="${d.id}" data-hierarchy="${hierarchy}"`));$('#cycleTailText').select();
  }
  function tailButtonsHTML(d,selected=selection()){return d.nodes.filter(n=>!n.tailHidden&&!d.edges.some(e=>e.source===n.id)).map(n=>`<div class="cycle-tail ${selected.kind==='tail'&&selected.id===n.id?'selected':''}" style="left:${cycleAnchorPoint(n,{angle:0}).x}px;top:${n.y+CYCLE_NODE.height/2-13}px"><button type="button" class="cycle-tail-line" data-cycle-tail="${n.id}" aria-label="${esc(n.text)}の追加用の線" aria-pressed="${selected.kind==='tail'&&selected.id===n.id}" title="クリックして選択、Deleteでこの線を削除"><span></span></button>${btn('cycle-add-tail','＋',null,'cycle-tail-plus',`data-id="${n.id}" title="この末端にノードを追加して接続" aria-label="${esc(n.text)}の先に追加して接続"`)}</div>`).join('');}
  function anchorHandlesHTML(d,selected){if(selected.kind!=='edge')return '';const e=cycleGeometry(d).edges.find(e=>e.id===selected.id);if(!e)return '';return ['source','target'].map((end,i)=>{const p=e[end+'Point'];return `<button type="button" class="cycle-anchor-handle" data-cycle-anchor="${e.id}" data-end="${end}" style="left:${p.x-12}px;top:${p.y-12}px" aria-label="${i?'遷移先':'遷移元'}の接続位置" title="${i?'遷移先':'遷移元'}の接続位置：ドラッグまたは矢印キーで調整"></button>`;}).join('');}
  function edgeButtonsHTML(d){return cycleGeometry(d).edges.map(e=>btn('cycle-insert-edge','＋',null,'cycle-edge-plus',`data-id="${e.id}" style="left:${e.insertX-13}px;top:${e.insertY-13}px" title="矢印の途中にノードを挿入" aria-label="${esc(d.nodes.find(n=>n.id===e.source)?.text+'から'+d.nodes.find(n=>n.id===e.target)?.text)}の間に挿入"`)).join('');}
  function edgeHTML(d,selected){return cycleGeometry(d).edges.map(e=>`<g data-cycle-edge="${e.id}" class="cycle-edge ${selected.kind==='edge'&&selected.id===e.id||selected.kind==='nodes'&&selected.ids.includes(e.source)&&selected.ids.includes(e.target)?'selected':''}" role="button" tabindex="0" aria-label="矢印 ${esc(e.label||'条件なし')}"><title>${esc(e.label||'条件を編集')}</title><path class="cycle-edge-line" d="${e.path}" marker-end="url(#arrow-${d.id})"/><path class="cycle-edge-hit" d="${e.path}"/>${e.label?`<text x="${e.labelX}" y="${e.labelY}" text-anchor="middle">${esc(e.label.length>35?e.label.slice(0,35)+'…':e.label)}</text>`:''}</g>`).join('');}
  function rulesHTML(d){const list=cycleRules(d);return `<section class="cycle-rules-panel" aria-label="ルール一覧"><div class="cycle-rules-intro"><strong>適用範囲ごとのルール</strong><span>カードを選ぶと元の仕様を編集できます。</span>${btn('cycle-add-global-rule','図全体にルールを追加','plus')}</div><div class="cycle-rule-cards">${list.map(r=>btn('cycle-select-detail',`<span class="cycle-rule-scope">${esc(r.scope)}</span><span class="cycle-rule-text">${esc(r.item.text)}</span>${r.parent?`<small>詳細：${esc(r.parent.text)}</small>`:''}`,null,'cycle-rule-card',`data-node-id="${r.nodeId}" data-id="${r.item.id}"`)).join('')||'<p class="field-hint">ルールはまだありません。図全体、またはノードのプロパティから追加できます。</p>'}</div></section>`;}
  function contentHTML(){
    const f=found();if(!f)return '';const d=f.diagram,v=ui(),s=selection(),g=cycleGeometry(d),owner=rows().find(r=>r.node._key===f.owner);
    const nodes=d.nodes.map(n=>{const selected=s.kind==='nodes'?s.ids.includes(n.id):['node','detail'].includes(s.kind)&&(s.nodeId||s.id)===n.id,count=detailRows(n.details).length;return `<div class="cycle-node ${n.kind} ${selected?'selected':''} ${v.source===n.id?'connecting':''}" data-cycle-node="${n.id}" style="left:${n.x}px;top:${n.y}px;width:${CYCLE_NODE.width}px;height:${CYCLE_NODE.height}px" role="button" tabindex="0" aria-label="${esc(n.text)}" aria-pressed="${selected}"><svg class="cycle-node-shape" viewBox="0 0 200 108" preserveAspectRatio="none" aria-hidden="true">${n.kind==='input'?'<polygon points="24,3 197,3 176,105 3,105"/>':n.kind==='event'?'<polygon points="24,3 176,3 197,54 176,105 24,105 3,54"/>':n.kind==='decision'?'<polygon points="100,3 197,54 100,105 3,54"/>':`<rect x="3" y="3" width="194" height="102" rx="${['start','end'].includes(n.kind)?50:n.kind==='state'?32:n.kind==='phase'?18:5}"/>${n.kind==='screen'?'<path class="screen-titlebar" d="M4 23H196"/>':n.kind==='reference'?'<path class="reference-bars" d="M15 4V104 M185 4V104"/>':''}` }</svg><span class="cycle-node-kind">${CYCLE_KINDS[n.kind]}</span><span class="cycle-node-text">${esc(n.text)}</span>${n.kind==='reference'?btn('cycle-open-reference',esc(referenceTitle(n)),null,'cycle-reference-open',`data-id="${n.reference||''}" data-source-diagram="${d.id}" data-source-node="${n.id}" ${found(n.reference)?'':'disabled'}`):`<span class="cycle-node-details">${count?'詳細 '+count+' 件':'詳細を追加'}</span>`}</div>`;}).join('');
    return `<div class="cycle-heading"><div><h2>↻ ${esc(d.title)}</h2><p>${esc(owner?.node.name||'')} <span>· ${d.nodes.length} ノード / ${d.edges.length} 遷移</span></p></div><div class="cycle-heading-actions">${btn('cycle-toggle-rules','ルール一覧 ('+cycleRules(d).length+')',null,v.rulesOpen?'active':'',`aria-pressed="${v.rulesOpen}"`)}${btn('cycle-explorer','図のエクスプローラー','panel-left', '', 'title="編集中の図に絞ってエクスプローラーを表示"')}${btn('cycle-owner','ツリーグラフへ','tree')}</div></div><div class="cycle-tools">${Object.entries(CYCLE_KINDS).map(([kind,label])=>btn('cycle-add-node',label,'plus','',`data-kind="${kind}"`)).join('')}${btn('cycle-connect',v.connect?'接続を中止':'矢印で接続','link',v.connect?'primary':'',`aria-pressed="${v.connect}"`)}<span class="cycle-clipboard-tools">${btn('cycle-select-all','全選択',null,'','title="すべてのフローノードを選択（Ctrl / Cmd＋A）"')}${btn('cycle-copy','コピー',null,'',`title="選択したフローをコピー（Ctrl / Cmd＋C）" ${selectedNodeIds().length?'':'disabled'}`)}${btn('cycle-paste','貼り付け',null,'','title="フローを貼り付け（Ctrl / Cmd＋V）"')}${selectedNodeIds().length?`<span class="cycle-selection-count">${selectedNodeIds().length} 選択</span>${btn('cycle-clear-selection','解除',null,'ghost')}`:''}</span><span class="spacer"></span>${btn('cycle-zoom-out','−',null,'icon','aria-label="図を縮小"')}<span id="cycleZoom">${Math.round(v.zoom*100)}%</span>${btn('cycle-zoom-in','＋',null,'icon','aria-label="図を拡大"')}${btn('cycle-fit','全体表示')}${btn('cycle-actual','100%')}</div>${v.rulesOpen?rulesHTML(d):''}${v.connect?`<div class="cycle-connection-status">${v.source?'遷移先のノードをクリックしてください。同じノードを選ぶと自己ループになります。':'遷移元のノードをクリックし、続けて遷移先をクリックしてください。'}（Escで中止）</div>`:''}<div class="cycle-viewport" data-cycle-id="${d.id}" tabindex="0" aria-label="サイクル図のキャンバス"><div class="cycle-sizer" style="width:${g.width*v.zoom}px;height:${g.height*v.zoom}px"><div class="cycle-stage" style="width:${g.width}px;height:${g.height}px;transform:scale(${v.zoom})"><svg class="cycle-lines" width="${g.width}" height="${g.height}"><defs><marker id="arrow-${d.id}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="9" markerHeight="9" orient="auto-start-reverse" markerUnits="userSpaceOnUse"><path d="M0 0L10 5L0 10z" fill="#7594a7"/></marker></defs><g id="cycleEdges">${edgeHTML(d,s)}</g></svg><div id="cycleEdgeButtons">${edgeButtonsHTML(d)}</div><div id="cycleTailButtons">${tailButtonsHTML(d)}</div>${nodes}<div id="cycleAnchorHandles">${anchorHandlesHTML(d,s)}</div>${!d.nodes.length?'<div class="cycle-empty"><b>大まかな流れ・状態から記述</b><p>場面・状態・画面などのノードを追加し、矢印でつなぎます。<br>各ノードの詳細仕様・挙動は、選択後に右側で追加できます。</p></div>':''}</div></div></div><div class="graph-hint">ノードをドラッグして配置 · ノードを選んで詳細仕様・挙動を編集 · 矢印を選んで条件を編集 / ＋で途中に挿入 · 背景をドラッグして移動 / Ctrl＋ホイールで拡大縮小</div>`;
  }
  function remember(){const viewport=$('.cycle-viewport');if(viewport){const v=ui(viewport.dataset.cycleId);v.left=viewport.scrollLeft;v.top=viewport.scrollTop;}}
  function zoom(value,point){const viewport=$('.cycle-viewport');if(!viewport)return;const v=ui(),g=cycleGeometry(found().diagram),old=v.zoom,p=point||{x:viewport.clientWidth/2,y:viewport.clientHeight/2},x=(viewport.scrollLeft+p.x)/old,y=(viewport.scrollTop+p.y)/old;v.zoom=Math.max(.15,Math.min(2,value));$('.cycle-stage').style.transform=`scale(${v.zoom})`;$('.cycle-sizer').style.width=g.width*v.zoom+'px';$('.cycle-sizer').style.height=g.height*v.zoom+'px';$('#cycleZoom').textContent=Math.round(v.zoom*100)+'%';viewport.scrollLeft=x*v.zoom-p.x;viewport.scrollTop=y*v.zoom-p.y;remember();}
  function fit(){const viewport=$('.cycle-viewport');if(!viewport)return;const g=cycleGeometry(found().diagram);zoom(Math.min(1,(viewport.clientWidth-20)/g.width,(viewport.clientHeight-20)/g.height));viewport.scrollLeft=viewport.scrollTop=0;remember();}
  function centerNode(id){const n=found()?.diagram.nodes.find(n=>n.id===id),viewport=$('.cycle-viewport');if(n&&viewport){viewport.scrollLeft=(n.x+100)*ui().zoom-viewport.clientWidth/2;viewport.scrollTop=(n.y+54)*ui().zoom-viewport.clientHeight/2;remember();}}
  function select(s){if(!flushAll())return false;ui().selection=s;render();$('.inspector-content').scrollTop=0;return true;}
  function chooseNode(id,modifiers={}){if(!flushAll())return;const v=ui();if(v.connect){if(!v.source){v.source=id;v.selection={kind:'node',id};render();}else {const source=v.source;v.connect=false;v.source='';transact(store=>{const d=findCycle(store.cycles,currentId()).diagram,e=connectCycle(d,source,id);v.selection={kind:'edge',id:e.id};},'矢印を追加しました');}}else{if(modifiers.ctrlKey||modifiers.metaKey||modifiers.shiftKey){const ids=new Set(selectedNodeIds());ids.has(id)?ids.delete(id):ids.add(id);v.selection=nodeSelection([...ids]);}else v.selection={kind:'node',id};render();}$('.cycle-viewport')?.focus({preventScroll:true});}
  function selectAll(){if(!flushAll())return;const v=ui();v.connect=false;v.source='';v.selection=nodeSelection(found().diagram.nodes.map(n=>n.id));render();$('.cycle-viewport')?.focus({preventScroll:true});}
  const editingText=()=>!!document.activeElement?.closest('input,textarea,select,[contenteditable]:not([contenteditable="false"])');
  function clipboardText(){if(!flushAll())return null;try{return copyCycleSelection(found().diagram,selectedNodeIds());}catch(e){toast(e.message);return null;}}
  function copyEvent(e){if(!isActive()||$('#dialog').open||editingText()||!selectedNodeIds().length)return;if(hasGesture()){e.preventDefault();return;}e.preventDefault();const text=clipboardText();if(text&&e.clipboardData){e.clipboardData.setData('text/plain',text);toast('フローをコピーしました。別のタブにも貼り付けできます');}}
  function pasteEvent(e){if(!isActive()||$('#dialog').open||editingText())return;e.preventDefault();if(hasGesture())return;pasteText(e.clipboardData?.getData('text/plain')||'');}
  function pasteText(text,target={id:currentId(),doc:state().doc}){
    if(!isActive()||currentId()!==target.id||state().doc!==target.doc||!found(target.id)){toast('貼り付け先が変わりました。貼り付け先の図で再度操作してください');return false;}
    if(!flushAll())return false;const viewport=$('.cycle-viewport'),v=ui(),position={x:(viewport.scrollLeft+50)/v.zoom,y:(viewport.scrollTop+50)/v.zoom};let result;
    if(!transact(store=>{result=pasteCycleSelection(findCycle(store.cycles,target.id).diagram,text,position);}))return false;
    v.connect=false;v.source='';v.selection=nodeSelection(result.ids);render();centerNode(result.ids[0]);$('.cycle-viewport')?.focus({preventScroll:true});toast(`${result.nodeCount} ノード・${result.edgeCount} 本の矢印を貼り付けました`);return true;
  }
  async function copyClipboard(){const text=clipboardText();if(!text)return;try{if(!navigator.clipboard?.writeText)throw Error();await navigator.clipboard.writeText(text);toast('フローをコピーしました。別のタブにも貼り付けできます');}catch{modal('フローをコピー',`<p class="field-hint">この欄を選択したまま Ctrl / Cmd＋C でコピーしてください。</p><textarea id="cycleClipboardText" class="cycle-clipboard-text" aria-label="コピーするフロー" readonly>${esc(text)}</textarea>`,btn('close-dialog','閉じる'));$('#cycleClipboardText').focus();$('#cycleClipboardText').select();}}
  async function pasteClipboard(){if(!flushAll())return;const target={id:currentId(),doc:state().doc};try{if(!navigator.clipboard?.readText)throw Error();const text=await navigator.clipboard.readText();pasteText(text,target);}catch{if(!isActive()||currentId()!==target.id||state().doc!==target.doc)return;pendingPaste=target;modal('フローを貼り付け',`<p class="field-hint">この欄で Ctrl / Cmd＋V を押し、「貼り付ける」を選んでください。キャンバス上では直接 Ctrl / Cmd＋V も使えます。</p><textarea id="cycleClipboardText" class="cycle-clipboard-text" aria-label="貼り付けるフロー"></textarea>`,btn('close-dialog','キャンセル')+btn('cycle-confirm-paste','貼り付ける',null,'primary'));$('#cycleClipboardText').focus();}}
  function deleteSelected(diagram=false){const d=found()?.diagram;if(!d)return;const s=diagram?{kind:'diagram'}:selection();if(s.kind==='nodes'){const ids=new Set(s.ids),nodes=d.nodes.filter(n=>ids.has(n.id)),count=d.edges.filter(e=>ids.has(e.source)||ids.has(e.target)).length;modal('選択したフローを削除',`<p class="error-detail">${nodes.length} ノードと配下の詳細 ${nodes.reduce((count,n)=>count+detailRows(n.details).length,0)} 件、接続する矢印 ${count} 本を削除します。元に戻せます。</p>`,btn('close-dialog','キャンセル')+btn('cycle-confirm-delete','削除する','trash','danger',`data-diagram="${d.id}" data-kind="nodes" data-ids="${s.ids.join(' ')}"`));return;}if(s.kind==='tail'){transact(store=>{detailHolder(findCycle(store.cycles,d.id).diagram,s.id).tailHidden=true;},'追加用の線を削除しました。元に戻せます');return;}let description='この図とすべてのノード・詳細仕様・挙動・矢印を削除します。';if(s.kind==='node'){const n=d.nodes.find(n=>n.id===s.id),count=d.edges.filter(e=>e.source===s.id||e.target===s.id).length;description=`「${n.text}」と配下の詳細 ${detailRows(n.details).length} 件、接続する矢印 ${count} 件を削除します。`;}else if(s.kind==='detail'){const n=detailHolder(d,s.nodeId),item=detailRows(n.details||[]).find(r=>r.item.id===s.id).item;description=`「${item.text}」と配下の詳細 ${detailRows(item.children).length} 件を削除します。`;}else if(s.kind==='edge')description='選択した矢印を削除します。';if(s.kind==='diagram'){const refs=all().filter(x=>x.id!==d.id).flatMap(x=>x.nodes).filter(n=>n.reference===d.id).length;if(refs)description+=` この図への参照 ${refs} 件は残り、参照先が見つからない状態になります。取り消すと復元します。`;}modal('サイクル図の要素を削除',`<p class="error-detail">${esc(description)}\n元に戻す操作が可能です。</p>`,btn('close-dialog','キャンセル')+btn('cycle-confirm-delete','削除する','trash','danger',`data-diagram="${d.id}" data-kind="${s.kind}" data-id="${s.id||''}" data-node-id="${s.nodeId||''}"`));}
  function shiftDetail(delta){const s=selection();if(s.kind!=='detail')return;transact(store=>{const n=detailHolder(findCycle(store.cycles,currentId()).diagram,s.nodeId),r=detailRows(n.details||[]).find(r=>r.item.id===s.id),to=r.index+delta;if(to<0||to>=r.list.length)return;r.list.splice(r.index,1);r.list.splice(to,0,r.item);});}
  function addDetail(kind){const s=selection(),nodeId=s.kind==='node'?s.id:s.nodeId||'',item=createDetail(kind),parent=s.kind==='detail'?s.id:null;ui().selection={kind:'detail',nodeId,id:item.id};if(kind==='rule')ui().rulesOpen=true;transact(store=>{const holder=detailHolder(findCycle(store.cycles,currentId()).diagram,nodeId),list=parent?detailRows(holder.details||[]).find(r=>r.item.id===parent).item.children:(holder.details??=[]);list.push(item);},'詳細を追加しました');}
  const actions={
    'cycle-select-all':selectAll,'cycle-copy':copyClipboard,'cycle-paste':pasteClipboard,
    'cycle-clear-selection':()=>{select({kind:'diagram'});$('.cycle-viewport')?.focus({preventScroll:true});},
    'cycle-confirm-paste':()=>{const text=$('#cycleClipboardText').value,target=pendingPaste;$('#dialog').close();pendingPaste=null;if(target)pasteText(text,target);},
    'cycle-reset-anchors':b=>transact(store=>{const e=findCycle(store.cycles,currentId()).diagram.edges.find(e=>e.id===b.dataset.id);delete e.sourceAnchor;delete e.targetAnchor;},'接続位置を自動に戻しました'),
    'cycle-add-tail':b=>tailDialog(b.dataset.id),
    'cycle-confirm-tail':b=>{const text=$('#cycleTailText').value.trim(),kind=$('#cycleTailKind').value,label=$('#cycleTailLabel')?.value||'';if(!text){toast('内容を入力してください');return;}let result;if(transact(s=>{result=b.dataset.hierarchy==='true'?appendCycleHierarchy(rows(),s.cycles,b.dataset.target,{kind,text}):appendCycleNode(findCycle(s.cycles,b.dataset.diagram).diagram,b.dataset.target,{kind,text,label});},'末端に追加しました')){$('#dialog').close();open(result.diagramId,result.selection);}},
    'cycle-toggle-rules':()=>{ui().rulesOpen=!ui().rulesOpen;redrawCanvas();},
    'cycle-confirm-kind':()=>{if(flush(true))$('#dialog').close();},
    'cycle-open-reference':b=>{const source=found(b.dataset.sourceDiagram)?.diagram.nodes.find(n=>n.id===b.dataset.sourceNode),id=source?source.reference:b.dataset.id;if(found(id))open(id);else toast('参照先の図を設定してください');},
    'cycle-add-global-rule':()=>{ui().selection={kind:'diagram'};addDetail('rule');},
    'cycle-insert-edge':b=>edgeInsertDialog(b.dataset.id),
    'cycle-confirm-hierarchy-insert':b=>{const text=$('#cycleInsertText').value.trim(),kind=$('#cycleInsertKind')?.value,position=$('#cycleInsertPosition').value;if(!text){toast('内容を入力してください');return;}let result;if(transact(s=>{result=insertCycleHierarchy(rows(),s.cycles,b.dataset.target,{position,kind,text});},'項目を挿入しました')){$('#dialog').close();open(result.diagramId,result.selection);}},
    'cycle-confirm-edge-insert':b=>{const text=$('#cycleInsertText').value.trim(),kind=$('#cycleInsertKind').value;if(!text){toast('内容を入力してください');return;}let result;if(transact(s=>{result=insertCycleOnEdge(findCycle(s.cycles,b.dataset.diagram).diagram,b.dataset.id,{kind,text});},'矢印の途中にノードを挿入しました')){$('#dialog').close();open(b.dataset.diagram,{kind:'node',id:result.node.id});}},
    'cycle-create':b=>create(b.dataset.owner),
    'cycle-confirm-create':b=>{const title=$('#cycleTitle').value.trim();if(!title){toast('図の名前を入力してください');return;}const d=createCycle(title),owner=b.dataset.owner;$('#dialog').close();if(transact(s=>(s.cycles[owner]??=[]).push(d),'サイクル図を作成しました'))open(d.id);},
    'cycle-open':b=>open(b.dataset.id),
    'cycle-open-target':b=>{const {id,nodeId,detailId,edgeId}=b.dataset;open(id,detailId?{kind:'detail',nodeId,id:detailId}:nodeId?{kind:'node',id:nodeId}:edgeId?{kind:'edge',id:edgeId}:{kind:'diagram'});},
    'cycle-select-edge':b=>select({kind:'edge',id:b.dataset.id}),'cycle-close':b=>close(b.dataset.id),
    'cycle-owner':()=>{const f=found();if(f)showOwner(f.owner);},
    'cycle-select-diagram':()=>select({kind:'diagram'}),
    'cycle-select-node':b=>select({kind:'node',id:b.dataset.id}),
    'cycle-select-detail':b=>select({kind:'detail',nodeId:b.dataset.nodeId,id:b.dataset.id}),
    'cycle-discard':()=>{formDirty=false;render();},
    'cycle-add-node':b=>{const d=found().diagram,count=d.nodes.length,p=freeCyclePosition(d,80+(count%3)*290,110+Math.floor(count/3)*200),n=createCycleNode(b.dataset.kind,p.x,p.y);ui().selection={kind:'node',id:n.id};if(transact(s=>findCycle(s.cycles,d.id).diagram.nodes.push(n),'ノードを追加しました'))centerNode(n.id);},
    'cycle-add-detail':b=>addDetail(b.dataset.kind),
    'cycle-detail-up':()=>shiftDetail(-1),'cycle-detail-down':()=>shiftDetail(1),
    'cycle-connect':()=>{const v=ui();v.connect=!v.connect;v.source='';render();},
    'cycle-delete-selection':()=>deleteSelected(),'cycle-delete-diagram':()=>deleteSelected(true),
    'cycle-confirm-delete':b=>{const {diagram:id,kind,id:itemId,nodeId}=b.dataset;$('#dialog').close();transact(store=>{const f=findCycle(store.cycles,id),d=f.diagram;if(kind==='diagram')store.cycles[f.owner]=store.cycles[f.owner].filter(x=>x.id!==id);else if(kind==='nodes'){const ids=new Set(b.dataset.ids.split(' '));d.nodes=d.nodes.filter(n=>!ids.has(n.id));d.edges=d.edges.filter(e=>!ids.has(e.source)&&!ids.has(e.target));}else if(kind==='node')removeCycleNode(d,itemId);else if(kind==='edge')d.edges=d.edges.filter(e=>e.id!==itemId);else {const n=detailHolder(d,nodeId),r=detailRows(n.details||[]).find(r=>r.item.id===itemId);r.list.splice(r.index,1);}},'削除しました。元に戻せます');},
    'cycle-zoom-in':()=>zoom(ui().zoom*1.2),'cycle-zoom-out':()=>zoom(ui().zoom/1.2),'cycle-fit':fit,'cycle-actual':()=>zoom(1)
  };
  function redrawCanvas(){remember();$('.cycle-content').innerHTML=contentHTML();bind();}
  function bind(){
    cancelGesture=null;hasGesture=()=>false;
    const form=$('#cycleForm');if(form){form.oninput=()=>{formDirty=true;$('#cycleEditState').textContent='未適用の変更があります';};form.onsubmit=e=>{e.preventDefault();if(flush())toast('サイクル図を更新しました');};}
    if(form?.dataset.kind==='node')form.elements.kind.onchange=()=>{$('#cycleReferenceFields').hidden=form.elements.kind.value!=='reference';$('#cycleKindHint').textContent=CYCLE_HINTS[form.elements.kind.value]||'大まかな流れを書き、細則は下の詳細仕様・ルールに追加できます。';formDirty=true;$('#cycleEditState').textContent='未適用の変更があります';};
    const viewport=$('.cycle-viewport');if(!viewport)return;const id=viewport.dataset.cycleId,v=ui(id);viewport.scrollLeft=v.left;viewport.scrollTop=v.top;
    viewport.onscroll=remember;
    let gesture=null;
    hasGesture=()=>gesture!==null;
    const focusHandle=(edge,end)=>$(`[data-cycle-anchor="${edge}"][data-end="${end}"]`)?.focus({preventScroll:true});
    const paint=d=>{const s=selection(id);$('#cycleEdges').innerHTML=edgeHTML(d,s);$('#cycleEdgeButtons').innerHTML=edgeButtonsHTML(d);$('#cycleTailButtons').innerHTML=tailButtonsHTML(d,s);$('#cycleAnchorHandles').innerHTML=anchorHandlesHTML(d,s);};
    cancelGesture=()=>{if(!gesture)return false;const g=gesture;gesture=null;if(viewport.hasPointerCapture(g.pointerId))viewport.releasePointerCapture(g.pointerId);redrawCanvas();if(g.kind==='anchor')focusHandle(g.id,g.end);else $('.cycle-viewport')?.focus({preventScroll:true});return true;};
    viewport.onpointerdown=e=>{
      if(e.button!==0)return;const handle=e.target.closest('[data-cycle-anchor]');if(!handle&&e.target.closest('button'))return;const el=e.target.closest('[data-cycle-node]');if(!handle&&!el&&e.target.closest('[data-cycle-edge]'))return;
      if((handle||el)&&formDirty){if(!flushAll())return;$('.cycle-viewport')?.onpointerdown(e);return;}
      if(handle){const edge=cycleGeometry(found(id).diagram).edges.find(e=>e.id===handle.dataset.cycleAnchor);if(!edge)return;const end=handle.dataset.end;gesture={kind:'anchor',id:edge.id,end,nodeId:edge[end],anchor:edge[end+'Angle'],clientX:e.clientX,clientY:e.clientY,moved:false};}
      else if(el){const n=found(id).diagram.nodes.find(n=>n.id===el.dataset.cycleNode),selected=selectedNodeIds(id),ids=selected.includes(n.id)?selected:[n.id],positions=found(id).diagram.nodes.filter(n=>ids.includes(n.id)).map(n=>({id:n.id,x:n.x,y:n.y}));gesture={kind:'node',id:n.id,ids,positions,modifiers:{ctrlKey:e.ctrlKey,metaKey:e.metaKey,shiftKey:e.shiftKey},clientX:e.clientX,clientY:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop,moved:false,offsetX:0,offsetY:0};}
      else gesture={kind:'pan',clientX:e.clientX,clientY:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop};
      gesture.pointerId=e.pointerId;viewport.focus({preventScroll:true});viewport.setPointerCapture(e.pointerId);e.preventDefault();
    };
    viewport.onpointermove=e=>{
      if(!gesture)return;const g=gesture,dx=e.clientX-g.clientX,dy=e.clientY-g.clientY;
      if(g.kind==='pan'){viewport.scrollLeft=g.left-dx;viewport.scrollTop=g.top-dy;return;}
      if(g.kind==='node'&&v.connect)return;if(Math.abs(dx)+Math.abs(dy)>4)g.moved=true;if(!g.moved)return;
      const d=found(id).diagram;
      if(g.kind==='anchor'){
        const n=d.nodes.find(n=>n.id===g.nodeId),rect=viewport.getBoundingClientRect();g.anchor=cycleAnchorAt(n,(e.clientX-rect.left+viewport.scrollLeft)/v.zoom,(e.clientY-rect.top+viewport.scrollTop)/v.zoom,g.anchor.angle);
        paint({...d,edges:d.edges.map(edge=>edge.id===g.id?{...edge,[g.end+'Anchor']:g.anchor}:edge)});return;
      }
      g.offsetX=Math.max(-Math.min(...g.positions.map(n=>n.x)),Math.min(20000-Math.max(...g.positions.map(n=>n.x)),Math.round((dx+viewport.scrollLeft-g.left)/v.zoom)));
      g.offsetY=Math.max(-Math.min(...g.positions.map(n=>n.y)),Math.min(20000-Math.max(...g.positions.map(n=>n.y)),Math.round((dy+viewport.scrollTop-g.top)/v.zoom)));
      const moved=new Map(g.positions.map(n=>[n.id,{x:n.x+g.offsetX,y:n.y+g.offsetY}]));for(const [id,p]of moved){const el=viewport.querySelector(`[data-cycle-node="${id}"]`);el.style.left=p.x+'px';el.style.top=p.y+'px';}paint({...d,nodes:d.nodes.map(n=>moved.has(n.id)?{...n,...moved.get(n.id)}:n)});
    };
    viewport.onpointerup=e=>{
      if(!gesture)return;const g=gesture;gesture=null;if(viewport.hasPointerCapture(e.pointerId))viewport.releasePointerCapture(e.pointerId);
      if(g.kind==='pan'){remember();return;}
      if(g.kind==='anchor'){if(g.moved)transact(s=>{findCycle(s.cycles,id).diagram.edges.find(e=>e.id===g.id)[g.end+'Anchor']=g.anchor;});focusHandle(g.id,g.end);return;}
      if(g.moved){v.selection=nodeSelection(g.ids);transact(s=>{const d=findCycle(s.cycles,id).diagram;for(const p of g.positions){const n=d.nodes.find(n=>n.id===p.id);n.x=p.x+g.offsetX;n.y=p.y+g.offsetY;}});}else chooseNode(g.id,g.modifiers);
    };
    viewport.onpointercancel=()=>cancelGesture?.();viewport.onlostpointercapture=()=>{if(gesture)cancelGesture?.();};
    viewport.onclick=e=>{const tail=e.target.closest('[data-cycle-tail]'),edge=e.target.closest('[data-cycle-edge]');if(tail||edge){if(select(tail?{kind:'tail',id:tail.dataset.cycleTail}:{kind:'edge',id:edge.dataset.cycleEdge}))$('.cycle-viewport')?.focus({preventScroll:true});}};
    viewport.onkeydown=e=>{
      const handle=e.target.closest('[data-cycle-anchor]');
      if(handle&&['ArrowLeft','ArrowUp','ArrowRight','ArrowDown'].includes(e.key)){
        e.preventDefault();e.stopPropagation();if(gesture||!flushAll())return;const edgeId=handle.dataset.cycleAnchor,end=handle.dataset.end,edge=cycleGeometry(found(id).diagram).edges.find(e=>e.id===edgeId),step=(e.shiftKey?15:5)*(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1);
        transact(s=>{findCycle(s.cycles,id).diagram.edges.find(e=>e.id===edgeId)[end+'Anchor']={angle:(edge[end+'Angle'].angle+step+360)%360};});focusHandle(edgeId,end);return;
      }
      if(e.target.closest('button'))return;if(e.key==='Enter'||e.key===' '){const node=e.target.closest('[data-cycle-node]'),edge=e.target.closest('[data-cycle-edge]');if(node||edge){e.preventDefault();node?chooseNode(node.dataset.cycleNode,e):select({kind:'edge',id:edge.dataset.cycleEdge});$('.cycle-viewport')?.focus({preventScroll:true});}}
    };
    viewport.onwheel=e=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();if(gesture)return;const rect=viewport.getBoundingClientRect();zoom(v.zoom*(e.deltaY<0?1.1:1/1.1),{x:e.clientX-rect.left,y:e.clientY-rect.top});};
  }
  function keydown(e){if(!isActive())return false;if(hasGesture()){if(e.key==='Escape'){cancelGesture();return true;}if(e.key==='Delete'||(e.ctrlKey||e.metaKey)&&['a','c','v','z'].includes(e.key.toLowerCase()))return true;}if(!editingText()&&(e.ctrlKey||e.metaKey)){if(e.key.toLowerCase()==='a'){selectAll();return true;}if(e.key.toLowerCase()==='c'&&selectedNodeIds().length&&!flushAll())return true;}if(e.key==='Escape'&&ui().connect){ui().connect=false;ui().source='';redrawCanvas();return true;}return false;}
  function documentHTML(){return rows().filter(r=>state().cycles[r.node._key]?.length).map(r=>`<section class="cycle-document"><h2>${esc(r.node.name)} · サイクル図</h2>${state().cycles[r.node._key].map(d=>`<h3>↻ ${esc(d.title)}</h3><p>${esc(d.description)}</p>${d.details?.length?`<h4>図全体の仕様・ルール</h4>${detailRows(d.details).map(r=>`<p style="margin-left:${r.depth*16}px"><b>${DETAIL_KINDS[r.item.kind]}：</b>${esc(r.item.text)}</p>`).join('')}`:''}${d.nodes.map(n=>`<h4>${esc(n.text)} <small>${CYCLE_KINDS[n.kind]}</small></h4><p>${esc(n.description)}</p>${n.kind==='reference'?`<p>参照先：${esc(referenceTitle(n))}</p>`:''}${detailRows(n.details).map(r=>`<p style="margin-left:${r.depth*16}px"><b>${DETAIL_KINDS[r.item.kind]}：</b>${esc(r.item.text)}</p>`).join('')}`).join('')}<table><thead><tr><th>遷移元</th><th>条件・きっかけ</th><th>遷移先</th></tr></thead><tbody>${d.edges.map(e=>`<tr><td>${esc(d.nodes.find(n=>n.id===e.source)?.text)}</td><td>${esc(e.label)}</td><td>${esc(d.nodes.find(n=>n.id===e.target)?.text)}</td></tr>`).join('')}</tbody></table>`).join('')}</section>`).join('');}
  return {isActive,currentId,selectedRowKey,isRowSelected,chooseNode,copyEvent,pasteEvent,explorerState,hierarchyInsertDialog,tailDialog,open,create,tabsHTML,ownerHTML,ownerContentHTML,contentHTML,inspectorHTML,flush,remember,sync,reset,actions,bind,keydown,documentHTML,dirty:()=>formDirty,deleteSelected};
}
